### ISSUE TITLE
Nova API

### ISSUE THREAD

**Issue by luishmcmoreno** [wgenial/cartrolandofc#1]
Opa, vc assistiu a palestra deles na campus? Falaram que reescreveram parte do código.  Vc sabe se a API muda para 2016?

**Comment by jhmcnet** [comment]
Em busca da nova API também, ano passado precisava de uma que buscasse por liga, mas não encontrei. Se encontrar algo, postarei aqui.

**Comment by giovanigenerali** [comment]
Não vi a palestra infelizmente. Se vocês acharem algo informem aqui por favor. Obrigado

**Comment by roomoraaes** [comment]
Alguém tem alguma informação sobre uma suposta nova API?

**Comment by giovanigenerali** [comment]
Até o momento, sem novidades sobre a nova API do Cartola. Talvez quando lançarem o novo sistema será possível obter alguns dados mas acho difícil, pois como dito na palestra eles pensam em uma API pública somente num futuro, sem prazo. Vídeo da palestra [https://www.youtube.com/watch?v=P1Y0_UFlEs0](url)

**Comment by luishmcmoreno** [comment]
Galera, estive pensando com um amigo meu: Será que é possível montarmos um
projeto opensource colaborativo pra colocarmos dados reais das partidas de
futebol? Uma api no modelo Footstats, porém opensource e colaborativa.
Estaria disposto a participar do projeto.

Hoje a única API brasileira que eu conheço é o Footstats e é bem fraca. Nem
e-mail eles respondem. E as apis fora do Brasil não costumam ter dados
nacionais. E já vi que muita gente precisa.

Se vocês animassem um projeto eu animaria também.

Luis H. Moreno
Sistemas de Informação - PUC Minas

Em 29 de março de 2016 12:13, Giovani Generali notifications@github.com
escreveu:

**Comment by ftatarli** [comment]
Opa boa noite pessoal !!  Pô eu animo em fazer essa ideia, acho que da para ter uns desdobramentos bem interessantes. 

E outra dúvida, alguém tem o histórico do cartola do último ano ? Tenho poucas rodadas não consigo fazer o que quero. Estava escrevendo um código para baixar, mas parece que não está mais disponível. 

Valeu.

Filipe Tatarli

**Comment by giovanigenerali** [comment]
Consultem o https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md
