### ISSUE TITLE
Histórico de pontuação

### ISSUE THREAD

**Issue by andre-msantos** [wgenial/cartrolandofc#10]
Vi algumas APIs e os arquivos que deixou disponível, porém não encontrei a informação que eu precisava.

É possível obter o histórico de pontuação e cartoletas do jogador?

Obrigado

**Comment by giovanigenerali** [comment]
@andre-msantos você só consegue pegar a pontuação e valor do jogador da rodada passada. Veja essa chamada aqui [https://api.cartolafc.globo.com/atletas/mercado](https://api.cartolafc.globo.com/atletas/mercado)
