### ISSUE TITLE
Estatísticas de Scouts

### ISSUE THREAD

**Issue by devkaio** [wgenial/cartrolandofc#11]
Olá, Giovani. Primeiramente, gostaria de parabenizá-lo pelo ótimo projeto. Eu sempre acompanhei projetos que envolvem a API do CartolaFC. Um dos projetos que mais achei interessante foi o de [Scouts e Estatísticas do Cartola FC](http://scoutscartola.com/).

Pois bem, minha sugestão de melhoria para seu projeto é justamente o de **inserção de um módulo de análise de estatísticas de jogadores**. Eu consigo analisar através da API usando o [Fiddler4](https://www.telerik.com/download/fiddler), mas não possuo ainda o conhecimento de programação suficiente para fazer uma chamada usando JSON e mostrar numa interface html.

De toda forma, parabéns mais uma vez e muito obrigado por disponibilizar seu projeto publicamente.

**Comment by Coopermine** [comment]
Valeu por disponibilizar  Uma perguna, alias 2.

Como verificar pontuação do time por rodada?
Como verificar pontuação em tempo real pelo cadum?

Pesquisei meu time  assim..

`https://api.cartolafc.globo.com/time/bardobeto`

recebi esse retorno

```
{
atletas: [],
clubes: {},
posicoes: {},
status: {},
time: {},
patrimonio: 123.74,
esquema_id: 4,
pontos: 77.7699966430664,
valor_time: 122.57
}

```
Mas entrando no site do cartola, diz eu eu fiz 48.23 e meu patrimonio é 111.59.

Estou fazendo algo errado?

**Comment by pdrocaldeira** [comment]
Kaio, eu tenho um projeto de fazer isso aí no futuro. Problema é fazer sozinho hahaha.

Se quiser quebrar um galho, eu fiz uma tabela com os scouts igual a interface antiga, talvez possa te ajudar: https://github.com/pdrocaldeira/cartolafc-scouts

Eu não pretendo manter esse link da Amazon não porque eles vão me cobrar. O pessoal do [Cartolas FC](http://cartolasfc.com/paginas.php?pg=estatisticas) estão utilizando.

**Comment by giovanigenerali** [comment]
@kaiolockdown legal a sugestão, vou analisar e arrumar um tempo para programar isso.
@pdrocaldeira ficou bacana essa tabela, se quiser contribuir nesse projeto aqui fique à vontade.

**Comment by giovanigenerali** [comment]
vou manter esse em aberto pois o pessoal pode ajudar nessa sugestão também.

**Comment by renatotkr** [comment]
pessoal, alguem tem os dados do mercado da primeira rodada?

**Comment by devkaio** [comment]
Como mencionei antes, infelizmente _ainda_ não possuo conhecimento de programação necessário pra implementar as modificações que sugeri. No entanto, posso disponibilizar um **UI básica** do que pode ser implementado em nível de programação no [Cartrolando](http://cartrolandofc.com/). Em breve atualizo com mais informações.

@pdrocaldeira muito obrigado pela indicação. Será bastante útil.

@giovanigenerali muito obrigado pela consideração. É sempre bom contribuir com **projetos promissores**. Ficarei na torcida pelas novidades dessa input e em breve disponibilizarei melhorias nela para facilitar no que for preciso. Grande abraço :smiley:

**Comment by giovanigenerali** [comment]
@kaiolockdown tudo bem, qualquer contribuição é bem vinda!
@renatotkr acho que não tem disponível isso via API, também pelo que vi nem no site do CartolaFC tem essas informações. Se alguém souber, avisa aqui pls.

**Comment by giovanigenerali** [comment]
@renatotkr olha aqui [https://github.com/wgenial/cartrolandofc/issues/14#issuecomment-222847259](https://github.com/wgenial/cartrolandofc/issues/14#issuecomment-222847259), postei um fluxo  de exemplo que pode ajudar.

**Comment by renatotkr** [comment]
Giovani, obrigado!

_Atenciosamente,_
_Renato Moreno Takakura_

2016-05-31 20:05 GMT-03:00 Giovani Generali notifications@github.com:

**Comment by pdrocaldeira** [comment]
Acho que essa issue virou o fórum oficial do CartolaFC Devs.
Que se vale cornetar, está melhor que os Devs Oficiais do Cartola FC haha.

@giovanigenerali Convite aceito!

**Comment by giovanigenerali** [comment]
@kaiolockdown @pdrocaldeira @renatotkr, acabei de publicar a página de estatísticas [http://cartrolandofc.com/estatisticas.html](http://cartrolandofc.com/estatisticas.html) ainda tem coisas para implementar como dados das rodas passadas, gráficos, etc.. mas já é um começo.

**Comment by devkaio** [comment]
Bom, eu estava trabalhando em algumas UI aqui e lembrei que já havia utilizado uma UI muito simples, leve e que pode ser implementada no [CartrolandoFC](http://cartrolandofc.com/), contribuindo de forma positiva na experiência do usuário em relação à facilidade da aplicação.

O padrão de design utilizado é o **Flat Design com Bootstrap**. Chamado [Flat UI](http://designmodo.github.io/Flat-UI/), trata-se de um _Design Framework_ criado pela [Designmodo](https://github.com/designmodo) muito limpo e agradável. Acredito que posso usar o fork que fiz do CartrolandoFC para ir montando a UI enquanto os trabalhos na parte de programação avançada vão sendo implementadas ao longo do tempo.

@giovanigenerali ótima novidade! Mesmo sem os dados disponíveis ainda, é ótimo ver que as sugestões que indicamos estão chegando num resultado bacana. Aprecio muito seu empenho e dedicação. Parabéns e muito obrigado.

**Comment by pupato13** [comment]
Galera beleza?

Também sou desenvolvedor e pesquisando API para consumir do Cartola eu cheguei nesse post =D

Existe algum jeito de pegar os scouts por rodada? Ele devolve o scout do jogador de forma somada desde o primeiro jogo...

Tenho o interesse de ajudar como puder no meu tempo livre, pois quero desenvolver um programa que auxilie a escalação baseado em estatísticas matemáticas.

@giovanigenerali eu vi este tópico seu (https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md) e gostaria de saber: o que é slug?

Abrasss

**Comment by giovanigenerali** [comment]
@pupato13 acabei de responder seu email, veja esse comentário https://github.com/wgenial/cartrolandofc/issues/14#issuecomment-222847259  aqui acho que te ajuda. Abs.

O slug é como se fosse o ID do time, ele é único e quando você faz a busca por um time a API retornar esse parâmetro, veja abaixo. Após obter ele você pode chamar a API para obter informações desse time específico.

### busca geral de times, vai retornar info do time e o slug

[https://api.cartolafc.globo.com/times?q=slb%20encarnados](https://api.cartolafc.globo.com/times?q=slb%20encarnados)

``` javascript
[
 {
  time_id: 834723,
  nome: "SLB Encarnados",
  nome_cartola: "Giovani Generali",
  slug: "slb-encarnados",
  facebook_id: null,
  url_escudo_png: "https://s2.glbimg.com/-osjD_9SH1UpWHaxF6QM2_Vkg7M=/https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/svg_v2/escudo/004042477420160518185856",
  url_escudo_svg: "https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/svg_v2/escudo/004042477420160518185856",
  foto_perfil: "https://cartolafc.globo.com/static/img/placeholder_perfil.png",
  assinante: false
 }
]
```

### busca informações de um time específico, usar o slug do time.

https://api.cartolafc.globo.com/time/slb-encarnados

**Comment by pupato13** [comment]
@giovanigenerali esse tópico eu vi, inclusive te agradeço por compartilhar é de grande ajuda para montar a base de jogadores...

Vou dar uma brincada pra ver o que consigo fazer com as API's que você publicou!

Só uma dúvida: Existe alguma forma de pegar o scout completo de um jogador X por rodada? Por exemplo:
Jogador 1
Rodada 3
(A) - 1
(CA) - 0
(CV) - 0
(DD) - 0
(DP) - 0
(FC) - 11
(FD) - 0
(FF) - 2
(FS) - 1
(FT) - 0
(G) - 0
(GC) - 0
(GS) - 0
(I) - 0
(PE) - 5
(PP) - 0
(RB) - 13
(SG) - 0

**Comment by giovanigenerali** [comment]
@pupato13 scouts eu não achei nada ainda, vou pesquisar e ver se consigo achar algo. Se alguém souber avisa aqui, por favor.

**Comment by giovanigenerali** [comment]
@pdrocaldeira vc achou algo sobre isso? Na sua tabela você lista esses scouts por rodada?  Valeu

**Comment by MullerEsposito** [comment]
Olá, na antiga API do cartola nós conseguíamos consultar a pontuação de um time por rodada. Alguém sabe como fazer isso agora com a nova API?

**Comment by pupato13** [comment]
@MullerEsposito  Eu posso estar falando besteira (sou novo nesse lance de api do Cartola), mas faria da seguinte maneira:

Chamaria este endereço para pegar os jogadores do time específico:
https://api.cartolafc.globo.com/time/[slug do time]

Guardaria em uma variável os ids dos jogadores e chamaria este endereço abaixo:
https://api.cartolafc.globo.com/atletas/mercado

Com a lista dos ids dos jogadores, eu daria um find pesquisando por ids e vendo a propriedade Pontos_Num.

Esse endereço aqui na teoria retorna as parciais dos jogadores em tempo real, porém não consultei ainda durante o jogo para ver se é real
https://api.cartolafc.globo.com/atletas/pontuados

**Comment by MullerEsposito** [comment]
@pupato13 Nesse caso você está falando de pegar a pontuação da rodada atual do time X. No caso estou falando de pegar a pontuação de rodadas passadas.

**Comment by pupato13** [comment]
@MullerEsposito aí já não sei, eu também queria algo para resgatar a pontuação de jogador a jogador por rodada, mas não achei!

**Comment by giovanigenerali** [comment]
@pupato13 pegar a pontuação do jogador por rodada eu já passei que aqui nesse https://github.com/wgenial/cartrolandofc/issues/14#issuecomment-222847259 tem uma idéia.
@MullerEsposito isso que você está falando realmente não tem na API nova, infelizmente. Estou vendo se tem como fazer um esquema de descobrir isso, porque não conseguimos saber como estava a escalação do time na rodada 1 por exemplo, ai não dá para pegar nem a pontuação muito menos o scout do jogador. Os caras poderiam ter criado uma chamada na API, só liberaram um resumão de scouts.

**Comment by MullerEsposito** [comment]
@giovanigenerali Putz, mô retrocesso isso por parte do Cartola. Como vocês conseguem descobrir essas chamadas de API do cartola quando são lançadas?

**Comment by pupato13** [comment]
@giovanigenerali eu ainda não mexi com essa parte de autenticação, vi apenas as chamadas que não precisam de autenticação! Preciso implementar isso em C# pra ver como ele me traz o retorno.

**Comment by roomoraaes** [comment]
@MullerEsposito Cara, no sistema que eu montei para a minha liga, sempre que fecha o mercado, eu salvo as escalações de todos os times participantes no meu banco de dados. E ao final de cada rodada, eu gravo a pontuação de cada participante daquela rodada em meu banco de dados. Assim eu tenho o controle total das escalações e pontuações de cada rodada e consigo gerar relatórios ou manipular dados.

Da uma olhadinha depois. 
http://www.variosgoles.com.br/
Abraço.

**Comment by MullerEsposito** [comment]
@roomoraaes Cara ficou show o site da sua liga. No meu caso como eu não montei o banco de dados não tenho como resgatar essas escalações antigas. Bom mesmo seria se o Cartola tivesse mantido a API antiga onde podíamos consultar a pontuação de cada rodada de qualquer cartoleiro.

**Comment by roomoraaes** [comment]
@MullerEsposito Cara, esquece as pontuações anteriores, não tem mais como recuperá-las. Terá que começar a guardar a partir de agora. O cartola esta escondendo essas informações.

**Comment by pdrocaldeira** [comment]
@MullerEsposito Chegando tarde mas antes tarde do que nunca. Seguinte, o que você quer não tem jeito de fazer diretamente. Você vai ter que derivar os scouts por rodada pegando um snapshot da API de cada rodada e subtraindo pelo snapshot anterior.

Esse repositório aqui parece que tem os dados que vc quer, exceto pela primeira rodada.
https://github.com/thevtm/CartolaFCScraper

Eu tenho interesse em derivar esses dados mas só entro de férias dia 1. Se fizer algo antes disso e quiser divulgar, acho que todo mundo nessa thread tem interesse :)

**Comment by pupato13** [comment]
@pdrocaldeira cara eu estou desenvolvendo um robô pra pegar os scouts das rodadas anteriores e estou testando ainda, pois alguns jogadores ele trouxe com a pontuação errada. Acredito que consigo terminar até o fim desta semana, aí jogarei ele num banco de dados e compartilho o script aqui!

**Comment by giovanigenerali** [comment]
Pessoal, pelo que pesquisei os scouts por rodada não são liberados na API. No código do projeto eu já puxei via API o resumão dos scouts, mas por rodada não tem mesmo. Vou fechar esse issue pois ele fica inválido por não existir esse recurso. Obrigado pelos comentários etc... qualquer outro assunto abram issues, que não sejam dúvidas de programação claro!

**Comment by nenzinho** [comment]
@giovanigenerali Como você fez para encontrar essas API´s? Gostaria de saber pois posso aplicar em outros sites. Valeu!
