### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by dipedro** [wgenial/cartrolandofc#12]
Não consegui autenticar para buscar uma liga em especial usando a url: https://login.globo.com/api/authentication.
É essa url que tu está usando no site??
Chegou a utilizar essa url?

**Comment by giovanigenerali** [comment]
@dipedro dá uma lida nesse meu comentário [https://github.com/wgenial/cartrolandofc/issues/3#issuecomment-220145143](https://github.com/wgenial/cartrolandofc/issues/3#issuecomment-220145143) para entender como funciona o fluxo de autenticação [https://github.com/wgenial/cartrolandofc/issues/7#issuecomment-220813085](https://github.com/wgenial/cartrolandofc/issues/7#issuecomment-220813085) e veja esses arquivos [https://github.com/wgenial/cartrolandofc/blob/master/auth.php](https://github.com/wgenial/cartrolandofc/blob/master/auth.php) e [https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php](https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php)

**Comment by dipedro** [comment]
@giovanigenerali vlwzao, consegui fazer funcionar. Tu saberia me dizer como fazer pra abrir a página da globo mesmo de login, pro cara logar e a gente só pegar o token depois?

**Comment by giovanigenerali** [comment]
@dipedro infelizmente não sei como fazer esse redirect para a tela de login deles. Talvez se você criar um form e o usuário digitar o email/senha você faz o post e pega o token, só uma sugestão.

**Comment by dipedro** [comment]
@giovanigenerali sim sim dá pra fazer assim, mas aí fica meio tenso para os usuários, pois eu poderia muito bem ta salvando essas informações pra uso indevido. E com a chamada do login da globo seria melhor. E no caso, eu só faria a chamada pra fazer se a sessão estava aberta naquele link que tu postou pra verificar se o usuário está logado.

**Comment by luizmacfilho** [comment]
@giovanigenerali essa autenticação funciona também para os usuários que tem o cadastro pelo facebook?

**Comment by giovanigenerali** [comment]
@luizmacfilho não, funciona apenas para usuários cadastrados na Globo.com pois requer email e senha.

**Comment by giovanigenerali** [comment]
@luizmacfilho apenas complementando, você pode fazer o cadastro na Globo.com usando o mesmo email do seu facebook ai você cadastra uma senha. Fazendo assim, dá para usar essa autenticação. Fiz um teste aqui e deu certo acessando das 2 formas, via facebook (não usa a senha, entra via token entre CartolaFC x Facebook) e via autenticação direto na API (usa a senha do usuário na Globo.com).

**Comment by luizmacfilho** [comment]
@giovanigenerali muito obrigado, vou de grande ajuda :+1:
