### ISSUE TITLE
Consulta por CADUM e retorno diferente

### ISSUE THREAD

**Issue by Coopermine** [wgenial/cartrolandofc#13]
Valeu por disponibilizar Uma perguna, alias 2.

Como verificar pontuação do time por rodada?
Como verificar pontuação em tempo real pelo cadum?

Pesquisei meu time assim..

`https://api.cartolafc.globo.com/time/bardobeto`

recebi esse retorno

```
{
atletas: [],
clubes: {},
posicoes: {},
status: {},
time: {},
patrimonio: 123.74,
esquema_id: 4,
pontos: 77.7699966430664,
valor_time: 122.57
}
```

Mas entrando no site do cartola, diz eu eu fiz 48.23 e meu patrimonio é 111.59.

Estou fazendo algo errado?

**Comment by roomoraaes** [comment]
@Coopermine Não é possível efetuar a busca por CADUM como fazíamos ano passado. Agora é permitido apenas a busca apenas pelo SLUG do time.

Para buscar as parciais de um determinado time em tempo real, basta somar a pontuação dos atletas que será retornado do JSON, conforme você enviou o exemplo.

Não existe mais a possibilidade de recuperar as pontuações por uma determinada rodada. Apenas é exibida a pontuação total do mês.

**Comment by WMarlon** [comment]
https://api.cartolafc.globo.com/time/bar-do-beto

para formar o slug substitui os espaços por "-"

Pesquisa por CADUN ainda não vi nada, tb estou aguardando por que se o cartoleiro trocar o nome do time... tem que refazer as pesquisas...

**Comment by giovanigenerali** [comment]
fechando esse, qualquer coisa reabram.
