### ISSUE TITLE
Estudo estatístico

### ISSUE THREAD

**Issue by pcesar12** [wgenial/cartrolandofc#14]
Boa noite pessoal, para estudo estatístico alguém tem salvo o json do mercado da rodada 1 e 2? Eu só tenho salvo da 3 e 4(atual). Obrigado.

**Comment by giovanigenerali** [comment]
@pcesar12 o status do mercado das rodadas passadas não está disponível na API, pelo que pesquisei só é possível pegar essas informações por jogador mas tem que estar autenticado. 

O fluxo seria assim:

Fazer uma chamada aqui [https://api.cartolafc.globo.com/atletas/mercado](https://api.cartolafc.globo.com/atletas/mercado) para pegar o **atleta_id** de cada jogador.

Após isso, chamar essa [https://api.cartolafc.globo.com/auth/mercado/atleta/**atleta_id**/pontuacao](https://api.cartolafc.globo.com/auth/mercado/atleta/[atleta_id]/pontuacao)  passando o atleta_id. Ela retorna o seguinte:

``` javascript
[
  {
    "atleta_id": 62121,
    "rodada_id": 1,
    "pontos": 4,
    "preco": 13.97,
    "variacao": -1.03,
    "media": 4
  },
  {
    "atleta_id": 62121,
    "rodada_id": 2,
    "pontos": -2,
    "preco": 11.07,
    "variacao": -2.9,
    "media": 1
  },
  {
    "atleta_id": 62121,
    "rodada_id": 3,
    "pontos": -0.5,
    "preco": 9.83,
    "variacao": -1.24,
    "media": 0.5
  },
  {
    "atleta_id": 62121,
    "rodada_id": 4,
    "pontos": 1,
    "preco": 9.46,
    "variacao": -0.37,
    "media": 0.62
  },
  {
    "atleta_id": 62121,
    "rodada_id": 5,
    "pontos": null,
    "preco": null,
    "variacao": null,
    "media": null
  },
...
```

Lembrando que essa chamada precisa usar token, pois não é pública. Para isso consulte esse [https://github.com/wgenial/cartrolandofc/issues/3#issuecomment-220145143](https://github.com/wgenial/cartrolandofc/issues/3#issuecomment-220145143) para saber como fazer isso. No código do projeto tem esses arquivos [https://github.com/wgenial/cartrolandofc/blob/master/auth.php](https://github.com/wgenial/cartrolandofc/blob/master/auth.php) e [https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php](https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php) que são exemplos de como autenticar e pegar o token

**Comment by pcesar12** [comment]
@giovanigenerali Show de bola, vou usar esse método para pegar essa informação retroativa. De fato seria muito mais rápido pelo json do mercado rsrs já está tudo junto os jogadores, só me liguei em salvar sem executar o truncate da tabela no database agora na rodada 4 e por sorte eu tinha o json da rodada anterior salvo em um backup de script. Obrigado pela sugestão :+1:

**Comment by giovanigenerali** [comment]
@pcesar12 blz, qlq coisa avisa!

**Comment by lourencoerick** [comment]
@pcesar12 poderia compartilhar os json das rodadas que vc tem ?
