### ISSUE TITLE
Status do Mercado

### ISSUE THREAD

**Issue by pabloruan0710** [wgenial/cartrolandofc#15]
Olá alguém saberia me indicar como consigo o status do mercado?

Utilizei essa url https://api.cartolafc.globo.com/mercado/status, porem ela retorna um numero inteiro no status. Vocês teriam a descrição de cada status?

`{
  "rodada_atual": 5,
  **"status_mercado": 3,**
  "esquema_default_id": 4,
  "cartoleta_inicial": 100,
  "max_ligas_free": 2,
  "max_ligas_pro": 5,
  "max_ligas_matamata_free": 5,
  "max_ligas_matamata_pro": 5,
  "max_ligas_patrocinadas_free": 2,
  "max_ligas_patrocinadas_pro_num": 2,
  "game_over": false,
  "times_escalados": 3408156,
  "fechamento": {
    "dia": 1,
    "mes": 6,
    "ano": 2016,
    "hora": 17,
    "minuto": 30,
    "timestamp": 1464813000
  },
  "mercado_pos_rodada": false
}`

**Comment by giovanigenerali** [comment]
@pabloruan0710 o que sei são esses os status:

``` code
1 = Mercado aberto
2 = Mercado fechado
3 = Mercado em atualização
```

**Comment by roomoraaes** [comment]
4 = Mercado em Manutençao

**Comment by pabloruan0710** [comment]
vlw galera.
