### ISSUE TITLE
Imagem do Jogador - Imagem não encontrada

### ISSUE THREAD

**Issue by Coopermine** [wgenial/cartrolandofc#16]
De onde vocês estão pegando a foto do jogador?

estou tentando pelo link

https://s.glbimg.com/es/sde/f/2016/04/30/f19726285035dfcb3d3052e030335ebd_FORMATO.png

mas o arquivo não está la

O endereço abaixo não existe na globo.com
https://s.glbimg.com/es/sde/f/2016/04/30/f19726285035dfcb3d3052e030335ebd_FORMATO.png

**Comment by giovanigenerali** [comment]
@Coopermine nessa url da imagem você precisa substituir a palavra FORMATO por 80x80 ou 140x140.

**Comment by dipedro** [comment]
Deu certo Giovani. Valeu!
