### ISSUE TITLE
Scouts parciais durante Rodada

### ISSUE THREAD

**Issue by pabloruan0710** [wgenial/cartrolandofc#17]
Olá boa tarde!

Alguém sabe me dizer se com essa url (https://api.cartolafc.globo.com/atletas/mercado) consigo pegar os scouts parciais durante a rodada?

Ele me retorna o seguinte:

``` javascript
 "atletas": [
    {
      "nome": "José Roberto da Silva Júnior",
      "apelido": "Zé Roberto",
      "foto": "https://s.glbimg.com/es/sde/f/2016/05/01/ba32976a24a9a6f813303a9bcd016693_FORMATO.png",
      "atleta_id": 36612,
      "rodada_id": 6,
      "clube_id": 275,
      "posicao_id": 4,
      "status_id": 2,
      "pontos_num": 0,
      "preco_num": 8.82,
      "variacao_num": 0,
      "media_num": 1.27,
      "jogos_num": 3,
      "partida": {
        "clube_casa_id": 275,
        "clube_casa_posicao": 4,
        "clube_visitante_id": 264,
        "aproveitamento_mandante": [
          "",
          "",
          "",
          "",
          ""
        ],
        "aproveitamento_visitante": [
          "",
          "",
          "",
          "",
          ""
        ],
        "clube_visitante_posicao": 1,
        "partida_data": "2016-06-12 16:00:00",
        "local": "Arena Palmeiras",
        "valida": true,
        "placar_oficial_mandante": null,
        "placar_oficial_visitante": null,
        "url_confronto": "",
        "url_transmissao": ""
      },
      "scout": {
        "CA": 1,
        "FC": 4,
        "FS": 1,
        "PE": 4,
        "RB": 5
      }
}
```

Só que acredito que esses scouts da rodada passada! Quero pegar os scouts durante a rodada.

**Ou se teria um outro link pra pegar essas informações!!!!**

**Comment by giovanigenerali** [comment]
@pabloruan0710 da rodada em andamento que eu saiba não tem nada disponível. Você consegue apenas pegar os scouts das rodada passada como nesse seu exemplo ou fazer a autenticação na API e pegar todos os scouts das rodadas passadas.

**Comment by pabloruan0710** [comment]
Entendi @giovanigenerali queria algo pra alerta de gol, até criei com os scouts mas como é da rodada passada não adiantou rsrs, pois no meu script ficava monitorando o json e quando tivesse algum gol eu emitia um alerta.... ;/ sabe se tem algo semelhante para gols?

**Comment by giovanigenerali** [comment]
@pabloruan0710 segue abaixo uma sugestão, mas não cheguei a testar ainda.
- Lista todos os jogos de hoje (placar geral, mostra qualquer jogo de qualquer campeonato)
  [http://globoesporte.globo.com/temporeal/futebol/central.json](http://globoesporte.globo.com/temporeal/futebol/central.json)

**Exemplo, jogo do Brasil x Haiti**

``` javascript
{
 transmissao_id: 19216,
 status: "Em Andamento",
 fase_rodada: "2ª rodada",
 dia_semana: "Qua",
 time_casa: {
   penalti: null,
   placar: 0,
   sigla: "BRA",
   escudo: "http://s.glbimg.com//es/sde/f/organizacoes/2014/06/04/brasil_30x30_1.png",
  nome: "Brasil"
 },
 video_ao_vivo: "",
 tipo_transmissao: "lance_a_lance",
 hora: "20:30",
 nome_campeonato: "Copa América",
 url: "http://globoesporte.globo.com/futebol/futebol-internacional/jogo/08-06-2016/brasil-haiti",
 time_visitante: {
   penalti: null,
   placar: 0,
   sigla: "HAI",
   escudo: "http://s.glbimg.com//es/sde/f/organizacoes/2016/06/04/haiti-30_1.png",
   nome: "Haiti"
 },
 localizacao: "Florida Citrus Bowl",
 data: "08/06/2016",
 id: 200907
},
....
```

Pegar a url do retorno do jogo acima e construir uma chamada concatenando o "transmissao_id" que é 19216 mais ".json", ficando assim:

[http://globoesporte.globo.com/futebol/futebol-internacional/jogo/08-06-2016/brasil-haiti/19216.json](http://globoesporte.globo.com/futebol/futebol-internacional/jogo/08-06-2016/brasil-haiti/19216.json)

Além disso, dá para chamar a classificação dos 2 times desse jogo, mesmo esquema acima só substituir o ID 19216, pelo do jogo que você quer ver:

[http://globoesporte.globo.com/servico/temporeal/transmissao/19216/classificacao_por_fase](http://globoesporte.globo.com/servico/temporeal/transmissao/19216/classificacao_por_fase)

Faça testes e depois avisa aqui se funciona, pode ajudar outros a consumirem essas API.

**Comment by MullerEsposito** [comment]
@pabloruan0710 Cara eu tô pegando as parciais com essa API ==> https://api.cartolafc.globo.com/atletas/pontuados

**Comment by pabloruan0710** [comment]
@MullerEsposito essa ai só mostra os pontuados, queria uma que tivesse os scouts, tipo Passes Certos, Passes Errados, Gols. Encontrei essas duas aqui:

Retorna informações de jogos da rodada:
**http://globoesporte.globo.com/temporeal/futebol/central_4815_13.json**

Informa dados de uma partida especifica.
**http://globoesporte.globo.com/mg/futebol/brasileirao-serie-a/jogo/03-07-2016/cruzeiro-vitoria/mensagens.json**
