### ISSUE TITLE
Existe algum serviço que retorna a pontuação de um time em determinada rodada?

### ISSUE THREAD

**Issue by robertgmelo** [wgenial/cartrolandofc#18]
Na API nova do Cartola, existe um serviço similar ao serviço existente na API antiga:

**Buscar rodada anterior do time**

REST: http://api.cartola.globo.com/time/id/{id}/info.json
- **Rodada 1:** http://api.cartola.globo.com/time/id/{id}/rodada/1/info.json
- **Rodada 2:** http://api.cartola.globo.com/time/id/{id}/rodada/2/info.json
- **Rodada N:** http://api.cartola.globo.com/time/id/{id}/rodada/N/info.json

**Comment by giovanigenerali** [comment]
@robertgmelo infelizmente na nova API não tem isso, veja esse meu comentário aqui  https://github.com/wgenial/cartrolandofc/issues/14#issuecomment-222847259. Nele eu passei uma sugestão de como trazer os dados de cada jogador por rodada. Para saber quais jogadores estavam escalados no seu time na rodada 1 por exemplo, eu não sei. Se alguém souber, avisa aqui por favor.
