### ISSUE TITLE
Dúvidas de acesso ao API das Ligas

### ISSUE THREAD

**Issue by RenanMatias** [wgenial/cartrolandofc#19]
Olá,

Sou organizar de uma liga no cartola aqui da empresa, através da sua ajuda, consegui fazer várias melhorias nos números da liga e nos participantes através das API que vc disponibilizou, primeiramente, obrigado!

eu consigo acessar as APIs e coletar as informações que preciso através de VBA para o Excel, porem, eu gostaria de pegar o ranking de cada participante de cada rodada, para com o tempo, trazer a evolução do campeão.

Eu não consigo acessar a API da liga que tem essas informações (https://api.cartolafc.globo.com/auth/liga/liga-dos-campeoes-supof), informa que {"mensagem":"Usuário não autorizado."}.
Você diz que é preciso do token, portanto, minha dúvida é, como eu consigo esse token? como eu faço para autenticar meu acesso a esta API?

Obrigado pela ajuda!
abs,

p.s.: fiz um Pull requests nos APIs informando a API dos esquemas táticos.

**Comment by giovanigenerali** [comment]
@RenanMatias Agradeço os elogios, você pode dar uma olhada nesse comentário https://github.com/wgenial/cartrolandofc/issues/3#issuecomment-220145143 pois nele tem uma explicação de como fazer a autenticação. O pull request eu não recebi, você precisa fazer para esse projeto e não no seu.

**Comment by giovanigenerali** [comment]
Fechando esse, qualquer dúvida reabra. Obrigado

**Comment by RenanMatias** [comment]
Giovani, Dei uma olhada e consegui gerar o token, porem, não consigo continuar com a consulta a API, continua dando a mesma mensagem {"mensagem":"Usuário não autorizado."}.

poderia me explicar melhor como faço a autenticação passando no header a chave 'X-GLB-Token' com o valor do token?

**Comment by giovanigenerali** [comment]
@RenanMatias no comentário que postei acima eu usei o Postman para testar via Chrome mesmo, veja aqui como enviar headers em chamadas: [https://www.getpostman.com/docs/requests#headers](https://www.getpostman.com/docs/requests#headers)
Recomendo primeiro testar via Postman, depois pesquise como enviar headers na linguagem que você está codificando.

**Comment by RenanMatias** [comment]
@giovanigenerali Consegui!
porem, analisando o json da minha liga, reparei que os times que retornaram estão limitado em 20, e a liga tem 39 participantes. como faço para que me retorne todos os times?

**Comment by giovanigenerali** [comment]
@RenanMatias veja esse meu comentário aqui https://github.com/wgenial/cartrolandofc/issues/7#issuecomment-220813085 você precisa usar paginação.

**Comment by RenanMatias** [comment]
Show de Bola @giovanigenerali 

Muito obrigado!!!
