### ISSUE TITLE
Informações por rodada

### ISSUE THREAD

**Issue by roomoraaes** [wgenial/cartrolandofc#2]
Referente a nova API do cartola, existe alguma forma de buscar informações da escalação/pontuação de um time/jogador filtrando por determinada rodada?

**Comment by jhmcnet** [comment]
Existe um link que busque por liga?

**Comment by roomoraaes** [comment]
@jhmcnet  Existe esse link na api: https://api.cartolafc.globo.com/auth/liga/nome-da-liga

Porém, para acessar essa api é necessário estar autenticado no sistema da globo, pois é feita uma validação de tokens.

**Comment by giovanigenerali** [comment]
- Buscar por ligas direto na API sem token:
https://api.cartolafc.globo.com/ligas?q=nome-da-liga

- Sober filtro de rodada ainda não tenho nada, assim que eu tiver atualizo nesse aqui https://github.com/wgenial/cartrolandofc/blob/master/nova-api.txt

**Comment by aoliveira87** [comment]
Fiquei sabendo que não vão disponibilizar este ano, uma pena, não podemos fomentar ainda mais o game, o que ajudaria ele a dar mais visibilidade ao fantasy game. Caso descubra algo, compartilho com vocês!

valeu @giovanigenerali!

**Comment by roomoraaes** [comment]
Sim, esse ano o cartola esta um pouco mais fechado no seu mundinho.Mas mesmo assim, com as APIs que não necessitam de autenticação, já é possível fazer muitas brincadeiras. Tenho uma liga privada com alguns amigos. Fiz um controle utilizando a API do cartola. http://www.variosgoles.com.br/.

Dêêm uma olhada.

**Comment by giovanigenerali** [comment]
@roomoraaes ficou bem bacana seu site!

**Comment by aoliveira87** [comment]
Ficou bem legal mesmo, parabens @roomoraaes!

**Comment by aoliveira87** [comment]
@giovanigenerali estamos utilizando o seu sistema de parciais por rodada em um site que colaboro, show de bola, parabéns pelo trabalho!

**Comment by giovanigenerali** [comment]
Legal @aoliveira87 se puder poste o link do site para eu ver.

**Comment by aoliveira87** [comment]
@giovanigenerali ta aqui brother: http://goo.gl/6tc4WQ, pedi para inserir os créditos ao seu projeto!

Você conhece algum sistema de scouts ao vivo, de acordo com a partida igual a este: http://scouts.competicaocartolafc.com/competicao_cartolafc/public_html/scouts ???

**Comment by giovanigenerali** [comment]
@aoliveira87 valeu por indicar os créditos ao meu projeto. Sobre o sistema de scouts ao vivo só conheço esse que por sinal é nosso cliente na @wgenial :)
