### ISSUE TITLE
Acessar informações do Usuario autenticado

### ISSUE THREAD

**Issue by thiagosysth** [wgenial/cartrolandofc#21]
Olá, tudo bem? Primeiramente parabéns pelo trabalho e incentivo :)
Estou "brincando" um pouco com a api, e gostaria de saber se tem como pegar informações especificar do usuário logado, como o nome do time, ligas dele etc.
Consegui fazer a autenticação sem problemas.
Desde já agradeço

**Comment by giovanigenerali** [comment]
@thiagosysth tem sim, dá uma olhada nesse arquivo aqui https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md pois tem várias chamadas na API que podem te ajudar. obrigado pelos elogios!

**Comment by thiagosysth** [comment]
Bom dia,
Já tinha visto este arquivo, porem não eh disso que eu precisava.
No documento, só tem os links pra pesquisar o time por algum termo ou um slug especifico.
Eu precisava saber o slug do meu proprio time authenticado, supondo que eu não saiba o mesmo.
Ex: Vc entra com sua conta, ai queria listar informações especificas do seu time, depois eu entro com a minha, e lista do meu.
Mas consegui encontrar, depois de algumas horas no google kkkkk
pra quem precisar, seque abaixo os links:

//retornar informações do time do usuario logado:
https://api.cartolafc.globo.com/auth/time
https://api.cartolafc.globo.com/auth/time/info

//retornar todas as ligas do usuario logado:
https://api.cartolafc.globo.com/auth/ligas

Desde já agradeço

**Comment by giovanigenerali** [comment]
@thiagosysth legal, já atualizei o arquivo com mais essas chamadas.
