### ISSUE TITLE
Cartola - Ajuda com correção de um Json

### ISSUE THREAD

**Issue by nenzinho** [wgenial/cartrolandofc#22]
Olá! Alguém pode me ajudar a corrigir um Json referente ao Cartola FC?
Primeiramente, segue o código:

> <?php
> $json_str = file_get_contents("https://api.cartolafc.globo.com/time/fuque-66"); 
> $jsonObj = json_decode($json_str);
> $atletas = $jsonObj->atletas;
> foreach ( $atletas as $e )
>     {
>   echo "$e->pontos_num - $e->apelido"; 
>     }
> ?> 

Esta função retorna todos os jogadores e suas respectivas pontuações:

> 1.4 - Felipe Azevedo
> 8.4 - Maicon
> -0.3 - Ganso
> 15.8 - Arrascaeta
> 0 - Rodrigo Dourado
> 0.82 - Argel Fucks
> 18 - Alex Muralha
> 7.4 - Vitor Bueno
> 7.4 - Vitor Hugo
> 1.6 - Bruno Rangel
> 5.1 - Ernando
> 3.3 - Róger Guedes

Até aí tudo bem, consegui os pontos individuais de cada jogador. Depois disso, com o fim de somar estes valores para ter a pontuação total do time, acrescentei a função de soma da seguinte forma:

> <?php
> $json_str = file_get_contents("https://api.cartolafc.globo.com/time/fuque-66"); 
> $jsonObj = json_decode($json_str);
> $atletas = $jsonObj->atletas;
> $v = 0.0;
> foreach ( $atletas as $e )
>     {
>   echo "$e->pontos_num - $e->apelido"; 
>     echo $v += $e->pontos_num;
>     }
> ?> 

Trazendo o seguinte resultado:

> 1.6 - Bruno Rangel
> 1.67.4 - Vitor Hugo
> 9-0.3 - Ganso
> 8.75.1 - Ernando
> 13.83.3 - Róger Guedes
> 17.18.4 - Maicon
> 25.51.4 - Felipe Azevedo
> 26.90.82 - Argel Fucks
> 27.7215.8 - Arrascaeta
> 43.527.4 - Vitor Bueno
> 50.9218 - Alex Muralha
> 68.920 - Rodrigo Dourado
> 68.92 

Como se pode notar, a última linha consta o resultado exato da soma (68.92).
Contudo, as pontuações individuais ficaram embaralhadas (ex: 27.7215.8).
Como posso consertar isso? Grato.

**Comment by giovanigenerali** [comment]
@nenzinho tenta dessa forma:

``` php
<?php
    $json_str = file_get_contents("https://api.cartolafc.globo.com/time/fuque-66"); 
    $jsonObj = json_decode($json_str);
    $atletas = $jsonObj->atletas;
    $v = 0.0;
    foreach ($atletas as $e) {
        echo $e->pontos_num ." - ". $e->apelido . "<br>"; 
        $v += $e->pontos_num;
    }
    echo $v;
?>
```

**Comment by nenzinho** [comment]
Giovani, perfeito! Obrigado.

**Comment by giovanigenerali** [comment]
Blz @nenzinho!

**Comment by nenzinho** [comment]
Sem querer abusar, gostaria de fazer mais uma pergunta. Como se vê, o script retorna uma lista com todos os jogadores e suas respectivas pontuações, certo? Como eu poderia fazer para que essa lista ficasse em ordem crescente (do menor para o maior)? Grato.

**Comment by nenzinho** [comment]
Acho que me precipitei! Essa pontuação individual não é ao vivo, pensei que fosse. Enquanto a escalação é obtida pela API "https://api.cartolafc.globo.com/time/fuque-66", as pontuações individuais (ao vivo) estão em outra API (https://api.cartolafc.globo.com/atletas/pontuados).

A dúvida cruel: é possível associar essas duas APIs? Ou seja, selecionar apenas os jogadores escalados e mostrar as respectivas pontuações?

Fiz o seguinte:

> <?php
>     $json_str = file_get_contents("https://api.cartolafc.globo.com/time/rander-cns"); 
>     $jsonObj = json_decode($json_str);
>     $atletas = $jsonObj->atletas;
>     foreach ($atletas as $e) {
>         echo $e->apelido . "<br>"; 
>     }
> ?>
> 
> <?php
>     $json_str = file_get_contents("https://api.cartolafc.globo.com/atletas/pontuados"); 
>     $jsonObj = json_decode($json_str);
>     $atletas = $jsonObj->atletas;
>     foreach ($atletas as $e) {
>         echo $e->pontuacao ." - ". $e->apelido . "<br>"; 
>     }
> ?>

Retorna duas listas: a primeira com a escalação do time e a segunda com a pontuação de todos os jogadores que pontuaram, inclusive os que não foram escalados. 

> Marquinhos Gabriel
> Argel Fucks
> Luan
> Paulo André
> Bruno Henrique
> Marinho
> Diego Souza
> Balbuena
> Juan
> Ernando
> Diego Cavalieri
> Eduardo Sasha
> 
> 0 - Oswaldo de Oliveira
> 0 - Paulo Autuori
> 2.2 - Tiago Cardoso
> 3.7 - Fábio
> -2 - Edu Dracena
> 2.7 - Henrique
> 1.1 - Fernando Prass
> 7.3 - Grafite
> 3.1 - Cleiton Xavier 
> (.... etc...)

Gostaria de ter apenas uma única lista com nomes e pontuações, desconsiderando todos os que não foram escalados. De que maneira posso realizar esse cruzamento de informações?

**Comment by giovanigenerali** [comment]
@nenzinho sua dúvida é sobre lógica de programação  e não sobre a API, recomendo você dar uma lida nesse arquivo  [https://github.com/wgenial/cartrolandofc/blob/master/src/js/scripts.js](https://github.com/wgenial/cartrolandofc/blob/master/src/js/scripts.js) pois nele já tem essa lógica que você pergunta. Veja no trecho que lista a pontuação dos atletas, o código está em js mas da para traduzir para php.

**Comment by nenzinho** [comment]
Giovani, infelizmente não tenho conhecimento suficiente para conseguir fazer isso. Não sei programar, a intenção era apenas criar algo para "brincar" com os colegas da liga. Achei que eu estivesse chegando perto, mas vi que sem estudo aprofundado fica difícil. De qualquer maneira, agradeço a atenção. Considere o tópico como respondido e pode fechar se assim desejar. Valeu! ;)

**Comment by nenzinho** [comment]
@giovanigenerali Beleza Giovani, segui seus concelhos e estou estudando a lógica de programação. Estou procurando alternativas pra conseguir chegar no resultado que pretendo. Cheguei em uma parte que acredito ser bem simples para vocês (programadores). Pode me dar uma ideia sobre possíveis funções que eu posso usar?

A situação é a seguinte:
`echo $id; // chama uma lista contendo apenas alguns ID´s de jogadores` 
`echo $jogador; // chama uma lista contendo ID e o respectivo nome de TODOS os jogadores`

Exemplo das listas:

> **echo $id;**
> 68911
> 37705
> 87887
> 38431
> 73317
> 49651
> 37604
> 68954
> 68952
> 70944
> 86759
> 70360
> 
> **echo $jogador;**
> 42232 - Amaral
> 37601 - Tiago Cardoso
> 36591 - Leonardo
> 42234 - Cássio
> 36650 - Magno Alves
> 42236 - Bruno Teles
> 36612 - Zé Roberto
> 36940 - Oswaldo de Oliveira
> 37604 - Paulo André
> 36943 - Paulo Autuori
> 36540 - Juan
> 42247 - Danny Morais
> 42411 - Cuca
> 49673 - Júlio César
> 50313 - Elicarlos
> 49737 - Fernando Gabriel
> (etc...)

A lógica que pretendo é nesse sentido: 
Se **$id** constar em alguma linha de **$jogador**, quero que retorne a linha inteira. 

Já pensei em utilizar expressão regular, não sei se funciona. Pode me dar um help?

**Comment by giovanigenerali** [comment]
@nenzinho veja se essa função do php resolve http://php.net/manual/pt_BR/function.in-array.php também veja os exemplos. Pelo que você está dizendo seria pesquisar um $id em uma lista de jogadores (array).

**Comment by nenzinho** [comment]
@giovanigenerali Giovani, meu php está assim:

```
<?php
	$json_str = file_get_contents("https://api.cartolafc.globo.com/time/rander-cns"); 
    $jsonObj = json_decode($json_str);
	$id = "";
	$atletas = $jsonObj->atletas;
		foreach ($atletas as $e) {
		    $tudo = $e->atleta_id . "<br>";
			$id .= $tudo;
        }
	**echo $id;**
?>

<?php
    $json_str = file_get_contents("https://api.cartolafc.globo.com/atletas/mercado"); 
    $jsonObj = json_decode($json_str);
    $jogador ="";
	$atletas = $jsonObj->atletas;
	    foreach ($atletas as $e) {
			$tudo = $e->atleta_id . " - " . $e->apelido . "<br>";
			$jogador .=$tudo;
        }
	**echo $jogador;**
?>
```

**Comment by nenzinho** [comment]
@giovanigenerali De vagar acho que chego lá! Seguinte Gio, usei o Explode pra gerar Arrays com as ID´s. Ficou da seguinte forma:

```
$str = $id; // chama a string
$explode = explode('<br>', $str); // explode em Arrays

// Array ( [0] => 68911 [1] => 49651 [2] => 68954 [3] => 38431 [4] => 73317 [5] => 87887 [6] => 86759 [7] => 37705 [8] => 70944 [9] => 37604 [10] => 70360 [11] => 68952 [12] => )
```

Agora, com esses ID´s, posso chamar os jogadores e as respectivas pontuações (ao vivo).
Infelizmente só vou ter a oportunidade de testar durante o jogo, quando a API ficar disponível.
Entretanto, já adiantei alguma coisa. Gostaria que, por gentileza, avaliasse meu script, principalmente se há possíveis erros. Segue abaixo:

```
<?php
	// Transforma os IDs em Array
	$str = $id;
	$explode = explode('<br>', $str);
	
	// FICA ASSIM: Array ( [0] => 87887 [1] => 49651 [2] => 37604 [3] => 68911 [4] => 68954 [5] => 70944 [6] => 37705 [7] => 73317 [8] => 68952 [9] => 86759 [10] => 38431 [11] => 70360 [12] => )
	
	// Conecta a API de pontuações ao vivo
	$json_str = file_get_contents("https://api.cartolafc.globo.com/atletas/pontuados"); 
    $jsonObj = json_decode($json_str);
	
	// Busca pelo ID um jogador e retorna a Pontuação e Apelido
	$atletas = $jsonObj->atletas->$explode[0]; // Usa a ID 87887 como Array
	    foreach ($atletas as $e) {
			
			// Exibe pontuação e o jogador referente a ID
			echo $e->pontuacao . " - " . $e->apelido . "<br>"; 
        }
?>
```

No aguardo. Obrigado!

**Comment by nenzinho** [comment]
@giovanigenerali Amigo, por favor, me tira só essa duvida?

Tenho esse script bem curto:
```
<?php
	
	$json_str = '{
					"rodada":12,"atletas":
					{
						"x":{"apelido":"Oswaldo de Oliveira"},
						"y":{"apelido":"Paulo Autuori"}
					}
				}'; 
    $jsonObj = json_decode($json_str);
	$jogador = $jsonObj->atletas; //
	    foreach ($jogador as $e) {
			echo $e->apelido . "<br>"; 
        }

?>
```

Esse script imprime dois nomes:
> Oswaldo de Oliveira
> Paulo Autuori

Mas o que eu quero é chamar apenas o nome que está no objeto "x", ou seja, que imprima apenas Oswaldo de Oliveira. Eu tentei dessa forma:

```
<?php
	
	$json_str = '{
					"rodada":12,"atletas":
					{
						"x":{"apelido":"Oswaldo de Oliveira"},
						"y":{"apelido":"Paulo Autuori"}
					}
				}'; 
    $jsonObj = json_decode($json_str);
	$jogador = $jsonObj->atletas; //
	    foreach ($jogador as $e) {
			echo $e->x->apelido . "<br>"; 
        }

?>
```

O problema está no "echo $e->x->apelido". O que faço?
Valeu.

**Comment by giovanigenerali** [comment]
Apenas podemos auxiliar em dúvidas sobre o projeto em sí ou recursos da API, dúvidas sobre programação infelizmente não podemos ajudar.
