### ISSUE TITLE
Escalar Time

### ISSUE THREAD

**Issue by pabloruan0710** [wgenial/cartrolandofc#23]
Olá, será que tem algum jeito de escalar o time sem ser pelo site da globo?

**Comment by giovanigenerali** [comment]
@pabloruan0710 acho complicado ter que implementar todo esse fluxo de autenticação, controle etc.. tem ainda as questões de segurança etc.. mas nada é impossível. recomendo dar uma fuçada no código do próprio site deles e quem sabe estudar algo parecido.

**Comment by pabloruan0710** [comment]
Galera Reabrindo aqui só pra ajudar, para quem quer quebrar a cabeça e fazer escalação segue a URL.

**https://api.cartolafc.globo.com/auth/time/salvar**

Enviar JSON com o seguinte formato:

> ```
> [
>         "esquema": 3,
>         "atleta": [
>             37788,
>             71116,
>             39152,
>             50427,
>             87225,
>             62009,
>             81682,
>             87863,
>             78435,
>             68930,
>             90651,
>             62136
>         ]
> ```

Obs: O código dos atletas tem que ser no formato Int ->Inteiro!, e é obrigatório o envio do token no header  **"X-GLB-Token"**.

**Comment by mateusgrb** [comment]
@giovanigenerali Acho que seria interessante adicionar essa rota de salvar time ao nova-api.txt. O que achas?

**Comment by tarsomatos** [comment]
@pabloruan0710  isso é um GET e não um POST , correto?

**Comment by giovanigenerali** [comment]
@mateusgrb claro, o que vocês acharem de novo para API façam as alterações no arquivo (nova-api.txt) e enviem um pull request.

**Comment by pabloruan0710** [comment]
Utilizei POST!

**Comment by ghost** [comment]
@pabloruan0710 Qual a chamada pra listar os esquemas?

**Comment by giovanigenerali** [comment]
@makako acabei de incluir aqui https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md#L47

**Comment by ghost** [comment]
@giovanigenerali show de bola!

**Comment by pupato13** [comment]
Alguém conseguiu fazer essa chamada via postman e funcionar?

**Comment by pabloruan0710** [comment]
meu funcionou via post, só que tem q passar os codigos no formato Int
