### ISSUE TITLE
Error 404 nos dados retroativos

### ISSUE THREAD

**Issue by MateusNascimento** [wgenial/cartrolandofc#24]
@giovanigenerali primeiramente muito obrigado pela ajuda nessas api do cartola, também estou trabalhando em estudo estatístico. Acontece que eu estou tentando acessar o dados históricos de um jogador qualquer através da url https://api.cartolafc.globo.com/auth/mercado/atleta/38230/pontuacao, 
passando o glbId como header, através do getpostman.com como você recomendou mas a url está retornando um 404, sabe me dizer se a url mudou?

![print](https://cloud.githubusercontent.com/assets/7481277/16543469/913af4e2-40ac-11e6-9670-65c493fe2f84.jpg)

**Comment by giovanigenerali** [comment]
@MateusNascimento está normal, tem que confirmar se pegou o token válido e está enviado ele corretamente.

**Comment by MateusNascimento** [comment]
@giovanigenerali acho que eu não estou manjando o processo então, via o getpostman eu chamo a url https://login.globo.com/api/authentication passando o json {"payload":{"email":"mt8hard@gmail.com","password":"MINHA_SENHA","serviceId": 438}} e ele me retorna o glbId como na imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/7481277/16571072/a730816c-4229-11e6-80d1-e3c9b2733602.png)

Então eu pego esse glbId e chamo por exemplo a url https://api.cartolafc.globo.com/auth/time/info passando no header a chave X-GLB-Token com o valor do glbId como na imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/7481277/16571107/6d975060-422a-11e6-926a-13fc154d4fa6.png)

Mas como vc pode ver ele me retorna um 404, estou fazendo alguma coisa errada?

**Comment by giovanigenerali** [comment]
@MateusNascimento Na segunda chamada, onde está POST troca para GET pois o erro está ai. O POST você usa apenas para obter o token, o restante tudo GET.

**Comment by MateusNascimento** [comment]
@giovanigenerali cara era isso, funcionou!
Muito obrigado cara, valeu mesmo!

**Comment by LuscaLeal** [comment]
@giovanigenerali cara, eu to tentando usar essa url "https://login.globo.com/api/authentication" pra autenticar mas tá dando página não encontrada. Você tem alguma ideia se eu to fazendo alguma coisa errada ou se a url mudou mesmo?
