### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by Hainner** [wgenial/cartrolandofc#25]
Baixei o código e coloquei na HostGator mas não está funcionando. Não traz a parcial, jogador, nada... Nem a formatação do css. Alguém pode me ajudar?

**Comment by Hainner** [comment]
Eu só preciso de uma ajuda!!!

**Comment by giovanigenerali** [comment]
@Hainner infelizmente não posso ajudar com instalação do projeto, aqui tiramos dúvidas apenas sobre recursos da API. Recomento você entrar em contato com o suporte da HostGator.

**Comment by Hainner** [comment]
Olá Giovani,
Eu entendo... Já falei com a HostGator e a informação que me deram é que não há nenhum problema, sei que todos aqui utilizam seu código e funciona perfeitamente.Talvez eu esteja fazendo algo errado por isso gostaria, se possível, de seus serviços para me ajudar, me diz o valor, vamos acertar!!!

Atenciosamente,Hainner
Date: Mon, 4 Jul 2016 17:15:24 -0700

**Comment by Hainner** [comment]
Olha como fica!
![cartrolandofc](https://cloud.githubusercontent.com/assets/20270337/16591529/bbf39920-42b2-11e6-9306-25f3fcf92b36.png)

Como faço para te contactar fora daqui?
