### ISSUE TITLE
Ordenando por Atleta

### ISSUE THREAD

**Issue by RenanMatias** [wgenial/cartrolandofc#26]
Bom dia!

Uma dúvida, estou trabalhando com a API https://api.cartolafc.globo.com/atletas/mercado, nele, podemos acessar um array dos atletas, porem, esse array não vem por ordem alfabética.

é possível fazer essa ordenação? se sim, como eu consigo?

Obrigado!

**Comment by tarsomatos** [comment]
Creio que você terá que obter o array inteiro.. e você mesmo ordenar.. não existe uma método que já traga isso ordenado.

**Comment by pabloruan0710** [comment]
No meu código eu pego o array e depois do array eu ordeno igual o @tarsomatos citou.

**Comment by giovanigenerali** [comment]
Galera, tem que ordenar na mão mesmo esse array. Estou fechando esse, qualquer coisa reabram. Obrigado
