### ISSUE TITLE
Api mais simples e flexível - sugestão

### ISSUE THREAD

**Issue by renatorib** [wgenial/cartrolandofc#28]
Acredito que você não precisa de muita instrução pra criar um wrapper da api.

O único intuito de precisar de um wrapper, é que o cartola bloqueia requisições client-side fora de seus domínios, então necessita de um wrapper que faça requisição via server-side, e o retorne pra que você use no seu client-side.
Nenhum segredo até aqui.

Teu wrapper poderia ser muito mais simples e flexível. Pelo que entendi, hoje, você separa em diferentes comandos de acordo com o &api=[comando]&argumentos. E isso é legal, funciona bem.

Mas tu poderia fazer algo como isso: 
(não testei, escrevi aqui direto, pode conter bugs)

``` php
header("Access-Control-Allow-Origin: *");
header('Content-type: application/json');

function sendRequest($path, $baseUrl = "https://api.cartolafc.globo.com/"){
  $c = curl_init();
  curl_setopt($c, CURLOPT_SSL_VERIFYPEER, FALSE);
  curl_setopt($c, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($c, CURLOPT_FRESH_CONNECT, TRUE);
  curl_setopt($c, CURLOPT_URL, $baseUrl . $path);
  $result = curl_exec($c);
  curl_close($c);

  return $result;
}

if($_GET['path']){
  $arguments = $_GET;
  unset($arguments['path']);
  $path = $_GET['path'] . http_build_query($arguments);

  echo sendRequest($path);
}
```

Daí voce poderia fazer qualquer requisição da api do cartola sem precisar se preocupar em adicionar no novos "cases" código

Por exemplo:

```
Api: https://api.cartolafc.globo.com/pos-rodada/destaques
Sua API: http://cartrolandofc.com/load-api.php?path=pos-rodada/destaques

Api: https://api.cartolafc.globo.com/time/[slug do time]
Sua API: http://cartrolandofc.com/load-api.php?path=time/[slug do time]

Api: https://api.cartolafc.globo.com/times?q=[nome do time]
Sua API: http://cartrolandofc.com/load-api.php?path=times&q=[slug do time]
```

**Comment by giovanigenerali** [comment]
@renatorib agradeço a sugestão mas o intuito de deixar explícito cada estrutura da chamada para a API é para o pessoal poder entender melhor e ficar intuitivo. Mas claro que daria para deixar dessa forma que você sugeriu também. Obrigado

**Comment by renatorib** [comment]
@giovanigenerali de qualquer forma, criei um wrapper http://github.com/renatorib/cartola-api baseado na sua doc do `nova-api.md`, com esse esquema que comentei, pra usar numa aplicação que to começando, full-featured em React... Se quiser dar uma olhada =P
Nela eu implemento o auth junto também (https://github.com/renatorib/cartola-api/blob/master/public/index.php)
