### ISSUE TITLE
Lista de links API

### ISSUE THREAD

**Issue by henriqueraf** [wgenial/cartrolandofc#29]
Olá,

eu vi que você listou a maioria dos links dessa API para pegar os dados, mas eu vi também que em algumas dúvidas por aqui, vc listou alguns outros links.

Existe uma lista completa dos links com os dados completos, tanto público como privado?

Obrigado !

**Comment by tarsomatos** [comment]
https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md

**Comment by Coopermine** [comment]
Como pegar a pontuacao mensal de um time? Não tem nessa lista

**Comment by giovanigenerali** [comment]
@Coopermine não tem isso na API.
