### ISSUE TITLE
Scouts retroativos

### ISSUE THREAD

**Issue by leandropessini** [wgenial/cartrolandofc#30]
Boa tarde. Estou fazendo um estudo analisando a evolução dos scouts de cada jogador, não apenas dos pontos e preço. Preciso do json de todas as rodadas anteriores a atual para isso, pois no método retroativo (por jogador), tenho apenas pontuação e preço. Você tem backup do Json das rodadas? Poderia me fornecer? Obrigado!

**Comment by MateusNascimento** [comment]
Cara, eu tenho a partir da rodada 7 e não são todos tbm só os dessa URL https://api.cartolafc.globo.com/atletas/mercado que a trás a pontuação de todos os jogadores na ultima rodada. Eu tbm to querendo os JSONs das rodadas que tão me faltando, passa seu email ai que eu te mando os que eu tenho

**Comment by giovanigenerali** [comment]
fechando mas se alguém tiver essas informações, por favor reabra esse.

**Comment by viniciusmf0201** [comment]
Mateus poderia me passar esses json que você mencionou ter? Obrigado
viniciusmend@gmail.com

**Comment by vfonseca21** [comment]
@MateusNascimento você poderia me passar esses arquivos json?

**Comment by lourencoerick** [comment]
@MateusNascimento você poderia me passar esses arquivos json?

**Comment by ronaldoaf** [comment]
Eu peguei desse site http://www.scoutscartola.com/ no ano passado fiz um webscapper para que as informações de cada jogador

**Comment by lourencoerick** [comment]
@ronaldoaf pode compartilhar esse webscapper ?

**Comment by henriqueal** [comment]
@MateusNascimento você poderia me passar esses arquivos json?

**Comment by MateusNascimento** [comment]
@henriqueal este é o link do meu repositório atual, porém estão faltando algumas rodadas https://onedrive.live.com/?authkey=%21AOOHN-GWVC7Ow1A&id=B4DD2FA819AFE606%21141&cid=B4DD2FA819AFE606

@giovanigenerali uma sugestão, você poderia disponibilizar essa url na página principal do projeto juntamente com meu email para que o pessoal conseguir os JSON facilmente e colaborar com os que estão faltando.

**Comment by giovanigenerali** [comment]
@MateusNascimento esse link parece não estar público, deixa ele liberado que disponibilizo. você também pode criar um projeto no github e deixar para download direto.

**Comment by henriqueal** [comment]
@MateusNascimento, obrigado!

@giovanigenerali, eu consegui acessar o drive dele sem problemas.
