### ISSUE TITLE
Nova autenticação na API

### ISSUE THREAD

**Issue by brugomes1407** [wgenial/cartrolandofc#31]
Boa Noite,
Voce saberia me informar se foi implementado alguma nova autenticação nas API's?
Porque não estou mais conseguindo acessar as informações /auth/.
Eu vi as infos e tem uma nova autenticação http://cocoon.globo.com/v2/user/logged.
A suas extrações estão funcionando corretamente?
Obrigado Bruno

**Comment by giovanigenerali** [comment]
@brugomes1407 está normal, veja esse exemplo http://cartrolandofc.com/load-api-auth.php?api=liga&liga_slug=liga-do-ge essa página tem aqui no projeto se quiser dar uma olhada.

**Comment by brugomes1407** [comment]
@giovanigenerali Oi Giovani, obrigado pela rapida resposta!
Vou tentar descobrir o que aconteceu....sempre que estou fora do Brasil tenho problemas com essas API's autenticadas! 
Fique a vontade caso queira fechar a issue, deve ser um problema especifico meu! 
Estava conseguindo executar normalmente, mas obrigado pela ajuda! 
Abs

**Comment by giovanigenerali** [comment]
@brugomes1407 blz, qualquer coisa avisa aqui. abs
