### ISSUE TITLE
Dados das rodadas anteriores

### ISSUE THREAD

**Issue by lourencoerick** [wgenial/cartrolandofc#32]
Pessoal, muito massa o API, parabéns a todos. Queria saber se é possível acessar os dados de pontuação das rodadas anteriores ? minha ideia é criar um modelo estatístico.

**Comment by MateusNascimento** [comment]
Sim, esta duvida ja foi respondida aqui: https://github.com/wgenial/cartrolandofc/issues/14

**Comment by lourencoerick** [comment]
Vlw, Mateus!
