### ISSUE TITLE
Informacao do time em cada rodada

### ISSUE THREAD

**Issue by wlmfa** [wgenial/cartrolandofc#33]
Suas APIs me ajudaram e ainda me ajudam muito!

É possível consultar os dados dos times em rodadas anteriores e isso ainda nao consta na sua lista.

https://api.cartolafc.globo.com/time/[slug do time]/[rodada]
rodada = 1, 2 ,3, etc

infelizmente a informacao do mercado ainda nao está disponível... preciso muito da informacao daqui https://api.cartolafc.globo.com/atletas/mercado só que da primeira rodada, que é a unica que me falta. será que alguem tem salvo?

**Comment by giovanigenerali** [comment]
@wlmfa obrigado por compartilhar a url de consulta do time por rodada. sobre o mercado da primeira rodada eu infelizmente não tenho. Dá uma busca aqui nos issues que já vi o pessoal falando sobre isso, abs.
