### ISSUE TITLE
Projeto em python

### ISSUE THREAD

**Issue by GabrielRato** [wgenial/cartrolandofc#34]
Bom eu criei um projeto em python com base nessa API que você forneceu, estou criando um banco de dados e tals desenvolvi pouca coisa por enquanto (to aprendendo a linguagem), eu queria agradecer por vc ter disponibilzado todos esses dados. 
Se tu puder linkar nesse teu projeto para que a galera que tb tem interesse em analisar o BD pudesse dar uma olhada e ajudar no projeto eu ficaria grato.

**Comment by giovanigenerali** [comment]
@GabrielTF141 obrigado!
