### ISSUE TITLE
Url/API da nova funcionalidade do Cartola

### ISSUE THREAD

**Issue by MateusNascimento** [wgenial/cartrolandofc#35]
@giovanigenerali de boa cara?
Seguinte, a uns dias atrás o cartola lançou uma nova funcionalidade onde é possui analisar o seu desempenho nas rodadas passadas, junto com a pontuação dos jogadores e como os jogadores fizeram os pontos(scouts), segue a imagem abaixo:

![print](https://cloud.githubusercontent.com/assets/7481277/17421578/398e1e42-5a81-11e6-8405-34b9078a039c.png)

Eu estou afim de pegar os scouts retroativos dos jogadores, desde a rodada 1 e acredito que esta funcionalidade é a chave. Minha duvída é, você sabe a url/api desta funcionalidade? , senão, há um jeito de descobrir?

Agradeço a atenção.

**Comment by altitdb** [comment]
@MateusNascimento a URL é essa:

https://api.cartolafc.globo.com/time/{slug-time}/{rodada}

Exemplo:

https://api.cartolafc.globo.com/time/chickens-football-club/17

**Comment by MateusNascimento** [comment]
@altitdb muito obrigado!
Essa é a URL mesmo, mas sera que não existe uma maneira de fazer essa busca dos scouts por rodada através do atleta_id de um jogador?

**Comment by GabrielRato** [comment]
@MateusNascimento, acredito que oq vc precisa seja isso: https://api.cartolafc.globo.com/auth/mercado/atleta/atl_id/pontuacao. Eu criei uma aplicação em python que pega diversos dados, inclusive esse e passa para um arquivo .db, se quiser dá uma olhada no meu GitHub =D

**Comment by SidneyFM** [comment]
boa noite amigo, parabéns pelo excelente trabalho.
com esse API eu consigo implementar em um app feito pelo Cordova!?

**Comment by giovanigenerali** [comment]
@SidneyFM sim é só implementar as devidas chamadas para a API. obrigado!

**Comment by rafa-trr** [comment]
Alguém sabe se tem a url para pegar os placares da rodada passada ?
essa Url https://api.cartolafc.globo.com/partidas mostra os jogos da próxima rodada!!
Queria uma que mostrasse a rodada anterior com os placares de cada jogo..
Agradeço

**Comment by edilsonld** [comment]
@giovanigenerali, eu estou tentando iniciar algo com o ionic, mas no $http.get retorna null.
Estava vendo algo sobre esse problema e dizem que é sobre o CORS no serviço do cartola que estaria fazendo com que viesse null. Tu conseguiu fazer funcionar esse get?
Eu estou fazendo assim:         

var url = encodeURI("https://api.cartolafc.globo.com/time/Grêmio-FBDD/12");

```
    $http.get(url).success(function(data) {
        alert("msg ok:" + data);            
    }).error(function(data, status) {
        alert("msg erro:" + data);
    })
```

**Comment by giovanigenerali** [comment]
@edilsonld sim, nesse projeto aqui funciona. dá uma lida no código do projeto aqui e confirme com seu código se está compatível, fazer chamadas para API puramente via Ajax não funciona mesmo devido ao CORS. Exemplo dessa sua chamada usando o código do projeto aqui [http://cartrolandofc.com/load-api.php?api=busca-atletas&team_slug=Grêmio-FBDD/25](http://cartrolandofc.com/load-api.php?api=busca-atletas&team_slug=Grêmio-FBDD/25)
