### ISSUE TITLE
Quantidade de escalações por jogador

### ISSUE THREAD

**Issue by nicolassoarespinto** [wgenial/cartrolandofc#38]
Muito legal o trabalho de vocês, parabéns e obrigado. 

Vi que tem como conseguir a quantidade de escalações para os jogadores mais escalados. com:

https://api.cartolafc.globo.com/mercado/destaques

Alguém sabe se é possível conseguir essa informação para todos os jogadores? Melhor ainda, seria possível conseguir isso retroativamente?

**Comment by giovanigenerali** [comment]
Infelizmente não tem isso na API
