### ISSUE TITLE
Problemas na autenticação

### ISSUE THREAD

**Issue by ltavasilva** [wgenial/cartrolandofc#39]
Meu processo de autenticação estava funcionando perfeitamente.
Mas a partir de hoje começou a retornar a seguinte mensagem de falha na autenticação:
"Missing captcha object with challenge and response"

Acho que tornaram obrigatório o preenchimento do captcha.
E agora?

**Comment by giovanigenerali** [comment]
Os caras colocaram o captcha do Google para autenticar, com isso não tem como chamar a API direto pois retorna "Missing captcha object with challenge and response".
Eu não deixei essa chama na documentação justamente por não ter garantia de disponibilidade pois sabia que uma hora ou outra eles iriam bloquear, infelizmente isso aconteceu.
