### ISSUE TITLE
Tem algum endereço que você busca os times que fazem parte de determinada liga?

### ISSUE THREAD

**Issue by irgot** [wgenial/cartrolandofc#4]

**Comment by roomoraaes** [comment]
Sim.
https://api.cartolafc.globo.com/auth/liga/nome-da-liga
Porém é necessário estar logado com o cartola. Vai dar um pouquinho de trabalho, mas é possível utilizar sim.

**Comment by irgot** [comment]
Você sabe qual o tipo de autenticação utilizada?

**Comment by roomoraaes** [comment]
Cara, eu fiz o seguinte.
Enviei um post para a url: 
https://login.globo.com/api/authentication

Com o seguinte header:
{headers: {Content-Type : application/json; charset=UTF-8}}

E bom o seguinte body:
{"payload":{"email":"EMAIL_CARTOLA","password":"PASSWORD_CARTOLA","serviceId":438}}

E obtive o seguinte retorno:
{
  "id": "Authenticated",
  "userMessage": "Usuário autenticado com sucesso",
  "glbId": "14a8a0df87e47cc300377850d60ce0dd83038716d4a426f395451636a596e5733647a456b36686574654471695153787a696b39566d5a52724d3838627a714d674a496b36724e386d564f6655497646473a303a726f647269676f6d6f726165735f313340686f746d61696c2e636f6d"
}

O token de retorno você utilizará para requisitar as APIs bloqueadas por acesso.

**Comment by irgot** [comment]
Consegui pegar o token de acesso, porém a forma que você envia nas apis bloqueadas é através de Json também?

**Comment by roomoraaes** [comment]
Cara, não fiz o teste, mas quando voce esta dentro do cartola e requisita uma liga, ele chama a url:
https://api.cartolafc.globo.com/auth/ligas

E passa o id de autenticação no header da requisição. Da uma olhadinha no network.

**Comment by caioschiavo** [comment]
@irgot @roomoraaes tem como dar uma detalhada nesse codigo, porque nao consegui aqui

**Comment by irgot** [comment]
@caioschiavo eu estou fazendo testes ainda com o postman, não comecei a programação ainda.
Vou fazer um app android, porém estou com dificuldades para pegar as ligas por times.

Mas com a ajuda do @roomoraaes  já deu para dar uma adiantada nos testes.

**Comment by caioschiavo** [comment]
estou tentando autenticar da forma como o @roomoraaes descreveu mas estou tendo erro

**Comment by caioschiavo** [comment]
consegui aqui tbm

**Comment by irgot** [comment]
@roomoraaes valeu pela ajuda consegui exatamente como você falou. .
Tudo certinho..

**Comment by roomoraaes** [comment]
@irgot legal, boa sorte no seu desenvolvimento.
Poderia descrever com detalhes como você fez a requisição para ter acesso aos times da liga?
Acho que muita gente tem essa dúvida, inclusive eu. Falei apenas pela lógica, não saberia se iria resolver.

**Comment by caioschiavo** [comment]
@irgot iria ajudar bastante mesmo

**Comment by irgot** [comment]
Bem eu não desenvolvi o código ainda, porem através de testes com o postman (Chrome APP) deu certo.

Primeiro requisita o token através da pagina de autenticação
https://login.globo.com/api/authentication

POST /api/authentication HTTP/1.1
Host: login.globo.com
Content-Type: application/json
Cache-Control: no-cache

{"payload":{"email":"???","password":"????????","serviceId":438}}

você receberá uma resposta como abaixo:

{
  "id": "Authenticated",
  "userMessage": "Usuário autenticado com sucesso",
  "glbId": "1fbdd1397d06dee73a9145a5ef3135547724a6841694b424741446f66424a454b6f356b7765624c555a613145374977443954564c5747496b6365383650717a516c767439356c493464596e366b444f643a303a6972076f79"
}

você pega somente esse id e passa no cabeçalho do seguinte endereço:

https://api.cartolafc.globo.com/auth/liga/nome-da-liga

GET /auth/liga/nome-da-liga HTTP/1.1
Host: api.cartolafc.globo.com
Content-Type: application/json
X-GLB-Token: 1fbdd1397d06dee73a9145a5ef3135547724a6841694b424741446f66424a454b6f356b7765624c555a613145374977443954564c5747496b6365383650717a516c767439356c493464596e366b444f643a303a6972076f79
Cache-Control: no-cache

Você recebe o json com a liga e os times que fazem parte.

**Comment by caioschiavo** [comment]
@irgot consegui pelo postman tbm, mas não através dos códigos, mesmo usando o mesmo código do postman

**Comment by pupato13** [comment]
Rapaziada, alguém conseguiu fazer a chamada via AJAX?

Tentei da seguinte maneira abaixo e recebo o seguinte erro:

**Chamada:**
$.ajax({
            url: "https://login.globo.com/api/authentication",
            type: 'POST',
            dataType: 'json',
            contentType: "application/json",
            headers: { 'Content-Type': 'application/json; charset=UTF-8' },
            data: {
                "payload":
                    {
                        "email": "EMAIL",
                        "password": "SENHA",
                        "serviceId": 438
                    }
            },
            success: function (data) {

```
            console.log(data);
        },
        error: function (xmlHttpRequest, textStatus, errorThrown) {

            console.log(errorThrown);
        }
    });
```

**Erro:**
XMLHttpRequest cannot load https://login.globo.com/api/authentication. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:17475' is therefore not allowed access.

**OBS:** já tentei colocar o headers como headers: { 'Access-Control-Allow-Origin': '*' } e mesmo assim continua o erro.

**Comment by WellingtonOSilva** [comment]
Você conseguiu? 

Estou com o mesmo problema via requisição AJAX...
