### ISSUE TITLE
Problema com url da API

### ISSUE THREAD

**Issue by dipedro** [wgenial/cartrolandofc#41]
Utilizo a tua URL de busca de times de uma liga no meu app pra não ter que ter um usuário logado, mas recentemente ela não tá funcionando, o que foi que aconteceu??

[http://cartrolandofc.com/load-api-auth.php?api=liga&liga_slug=](url)

Tá dando erro de usuário não autorizado!

**Comment by felipethomas** [comment]
Estou tendo esse problema também. Quando acesso o site do cartola usando o mesmo usuário e senha que uso para autenticar pela url, dá certo, mas pela url sai a mensagem de usuário não autorizado. Esse problema começou depois do problema que aconteceu no cartola no último fim de semana (24/09/2016). Alguma pista sobre o problema?

**Comment by giovanigenerali** [comment]
Os caras colocaram o captcha do Google para autenticar, com isso não tem como chamar a API direto pois retorna "Missing captcha object with challenge and response".
Eu não deixei essa chama na documentação justamente por não ter garantia de disponibilidade pois  sabia que uma hora ou outra eles iriam bloquear, infelizmente isso aconteceu.

**Comment by dipedro** [comment]
Olá @giovanigenerali, realizando alguns testes aqui, consegui resolver o problema por enquanto. o/

Basta alterar o JSON de autenticação, ficando assim:

`{"captcha":"","payload":{"email":"seuemail@seuemail.com", "password":"suasenha","serviceId": 438}}`

O Captcha pode ir vazio mesmo, não tem problema.

Gostaria que se possível tu atualizasse a api do Cartrolando, pq não queria postar uma atualização do meu app pra que ele volte a funcionar. Pleaseeee

Abraço.

**Comment by felipethomas** [comment]
Valeu @dipedro, vou testar isso também. Obrigado por compartilhar.

Em ter, 27 de set de 2016 às 22:06, dipedro notifications@github.com
escreveu:

**Comment by giovanigenerali** [comment]
Vou testar aqui, me deem uns minutos.

**Comment by dipedro** [comment]
Carambaaaa a galera em peso, asuhuahua.
Eu testei aqui usando o Postman e funcionou tranquilo.

**Comment by giovanigenerali** [comment]
@dipedro publicado http://cartrolandofc.com/load-api-auth.php?api=atleta-pontuacao&atleta_id=3081
obrigado pela ajuda 👍

**Comment by felipethomas** [comment]
Testado e homologado :)
Valeu @dipedro e @giovanigenerali

**Comment by dipedro** [comment]
@giovanigenerali sem querer ser chato, mas a url que preciso continua sem funcionar.
![url nao funciona](https://cloud.githubusercontent.com/assets/12878726/18897951/c5d61df2-8504-11e6-8076-c206ba1ebc29.PNG)

Tu podes dar uma olhada? Sei que vou ter que fazer o meu mesmo, mas tô sem tempo pra realizar as alterações no meu app. Abraço.

**Comment by giovanigenerali** [comment]
@dipedro acho que agora está ok.
