### ISSUE TITLE
Autenticação Globo.com

### ISSUE THREAD

**Issue by juracyjunior** [wgenial/cartrolandofc#43]
Olá amigo!
Procurei pela internet e não encontrei onde explique como fazer a autenticação utilizando a página de login da própria Globo.com.
Quero utilizar este método no meu site/app, pois passa mais confiança para usuário.
A ideia é chamar este método e receber apenas o token. Sem precisar saber login e senha do usuáiro.
Desde já agradeço a atenção e ajuda.

**Comment by giovanigenerali** [comment]
@juracyjunior pelo que sei não existe nenhuma API que permita você fazer isso.
