### ISSUE TITLE
Documentação para a api pública do Cartola?

### ISSUE THREAD

**Issue by dyegonery** [wgenial/cartrolandofc#44]
Gostaria de saber se há alguma documentação em algum lugar para a API pública do cartola? Vi que você utiliza vários endpoints da mesma, mas gostaria de saber se há alguma documentação na próprio Globo sobre isso.

Um abraço!

**Comment by giovanigenerali** [comment]
@dyegonery Não tem porque teoricamente essa API não é pública. Os endpoints foram extraídos da própria aplicação atual do site deles. Abs

**Comment by dyegonery** [comment]
@giovanigenerali Mas e quanto a esses endpoints, que você indicou aqui?
https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md

Você os encontrou vasculhando a própria aplicação do Cartola?

**Comment by giovanigenerali** [comment]
@dyegonery exato!

**Comment by dyegonery** [comment]
@giovanigenerali Entendi. To tentando entrar em contato com um membro da equipe de dev deles pra saber se há alguma API pública. Se houver, te aviso por aqui. Mas obrigado, desde já. :D

**Comment by giovanigenerali** [comment]
@dyegonery Pelo que vi no vídeo https://youtu.be/P1Y0_UFlEs0 de apresentação dessa API eles não pretendem de momento abrir mas se conseguir algo avisa aqui. Abs
