### ISSUE TITLE
Imagens /times?q=nome não abre

### ISSUE THREAD

**Issue by pabloruan0710** [wgenial/cartrolandofc#45]
Alguém sabe como abrir as imagens este ano? 

Estou utilizando este endpoint https://api.cartolafc.globo.com/times?q=pel

e não consigo o visualizar as imagens dos times, até consigo listar, mas o link não abre.

> "time_id": 5786976,
"nome": "Peladeiros1983",
"nome_cartola": "Vagner",
"slug": "peladeiros1983",
"facebook_id": null,
"url_escudo_png": "https://s2.glbimg.com/fXg6TLK-yrPORY-HtiFET-_-Pf8=/https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/svg_v2/escudo/003849931620160610133935",
"url_escudo_svg": "https://s3.glbimg.com/v1/AUTH_58d78b787ec34892b5aaa0c7a146155f/svg_v2/escudo/003849931620160610133935",
"foto_perfil": "",
"assinante": false

**Comment by giovanigenerali** [comment]
@pabloruan0710 eles mudaram o retorno do escudo dos times, vou dar uma olhada para ver se descubro.

**Comment by pabloruan0710** [comment]
O que pode ter acontecido é que todo ano zerava o escudo, as vezes zeraram, ou algo assim, fiquei esse período todo procurando algo e nada @giovanigenerali

**Comment by giovanigenerali** [comment]
@pabloruan0710 consegui pegar apenas na lista de atletas, lá tem info do time e nesse as imagens abrem. meu ultimo commit já está com a correção https://github.com/wgenial/cartrolandofc/commit/00908e17d74b788e3031fe11f9d737964b00ec37?diff=split#diff-965f6341f1973f97f5552661f66c610dR491 e no site está atualizado http://cartrolandofc.com/
