### ISSUE TITLE
POST Escalação

### ISSUE THREAD

**Issue by ghost** [wgenial/cartrolandofc#47]
Olá, estou tentando dar um post passando auth + header, porém recebo a seguinte mensagem:

"mensagem": "Houve algum problema e seu time não foi escalado. Tente novamente!"

passei os seguintes id's (todos os jogadores são validos e correspondem ao esquema)
[
 	"esquema": 3,
 	"atleta": [
 		84266,
 		63110,
 		86779,
 		51549,
 		91664,
 		90535,
 		38219,
 		92850,
 		95627,
 		91003,
 		87391,
 		36943
 	]
 ]

Você tem alguma ideia do que pode estar acontecendo?

Grato desde já!

**Comment by pabloruan0710** [comment]
@SportsMobile estranho, fiz o teste agora com a seguinte escalação

> {"esquema":3,"atleta":[82768,70046,86764,38394,83786,38440,50324,92193,62119,94068,82952,37245]}

e o Retorno foi bem satisfatório

> HTTP/1.1 200 OK
Date: Mon, 10 Apr 2017 12:16:42 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 41
Connection: close
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: https://cartolafc.globo.com

`{"mensagem":"Time` Escalado! Boa Sorte!"}

**Comment by ghost** [comment]
Consegui, estava usando [] ao invés de {}
Obrigado meu caro!

**Comment by giovanigenerali** [comment]
Fechando ;)
