### ISSUE TITLE
API 2017 - Status Code 403

### ISSUE THREAD

**Issue by geovannefduarte** [wgenial/cartrolandofc#48]
Olá,

a API está retornando o status code 403 depois da semana de testes.
Será que a API vai mudar?

**Comment by pabloruan0710** [comment]
@geovannefduarte está de volta! return 200

**Comment by geovannefduarte** [comment]
Obrigado =)

**Comment by alexrocha161010** [comment]
Não está retornando, apenas está carregando :( só  o meu será?

**Comment by pabloruan0710** [comment]
Semana q vem vai ser liberado oficialmente!!
