### ISSUE TITLE
Retorno API Slug Time 2017

### ISSUE THREAD

**Issue by roomoraaes** [wgenial/cartrolandofc#49]
Pessoal, não consegui acompanhar as rodadas teste do cartola 2017.
Alguém salvou o JSON de retorno da api abaixo?

https://api.cartolafc.globo.com/time/slug/[slug do time]

Quero saber como a pontuação será disponibilizada.
Como a rodada ainda esta aberta, ele não exibe a pontuação. Alguém salvou o retorno de uma rodada fechada?

**Comment by giovanigenerali** [comment]
Acho que ninguém pois como era teste não tinha muito valor, mas se alguém souber e tiver só reabrir esse.
