### ISSUE TITLE
Buscar a pontuação do time na rodada continua igual no ano passado?

### ISSUE THREAD

**Issue by caioschiavo** [wgenial/cartrolandofc#52]
pega a info do time e soma os jogadores?

vou tentar fazer aqui, são 300 times..rs

**Comment by jhonata-menezes** [comment]
Esse é o primeiro ano que estou usando a api, mas provavelmente é nesse endpoint que retorna : https://api.cartolafc.globo.com/time/id/4
ou
https://api.cartolafc.globo.com/time/slug/3color
@giovanigenerali pode confirmar isso, alias adiciona esse link nos [endpoint's mapeados](https://github.com/wgenial/cartrolandofc/blob/master/api-cartolafc-2017.txt), eu percebi que nao tem, apesar de retornar os mesmos dados passando o slug.

**Comment by giovanigenerali** [comment]
@jhonata-menezes feito, mas se quiserem dá para baixar o projeto - alterar - mandar pull request! Nem sempre consigo contribuir aqui, abs!

**Comment by giovanigenerali** [comment]
@jhonata-menezes @caioschiavo 

https://github.com/wgenial/cartrolandofc/blob/master/src/js/scripts.js#L590

só fiquem de olho se os caras não vão mudar o retorno na de 2017, nem peguei quando abriram o beta desse ano.

abs

**Comment by VICTORCOSTA10** [comment]
@giovanigenerali, mandei um email para vc pelo WGenial, me responde ok...
