### ISSUE TITLE
Como eu poderia usar essa API em PHP?

### ISSUE THREAD

**Issue by pemartins** [wgenial/cartrolandofc#54]
Estou tentando usar os links de API fornecidos. Quando acesso diretamente via browser, ele me retornao JSON correto. Quanto tento acessar via aplicação PHP, é retornado um BOOLEAN FALSE.

1- Preciso autenticar na aplicação para poder acessar o link via backend? 

Meu código:
<?php

echo '<pre>';

error_reporting(1);
function file_get_contents_curl($url) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_POST, false);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
    curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);

    $data = curl_exec($ch);
    curl_close($ch);

    return $data;
}

var_dump(file_get_contents_curl('https://api.cartolafc.globo.com/mercado/status/'));

?>

**Comment by jhonata-menezes** [comment]
Tente dessa forma

```php
error_reporting(1); 
function file_get_contents_curl($url) { 
  $ch = curl_init(); 
  curl_setopt($ch, CURLOPT_POST, false); 
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET"); 
  curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE); 
  curl_setopt($ch, CURLOPT_HEADER, 0); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0); 
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
  curl_setopt($ch, CURLOPT_URL, $url); 
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36'
    ));
  $data = curl_exec($ch); curl_close($ch); 
  return $data; 
} 
var_dump(file_get_contents_curl('https://api.cartolafc.globo.com/mercado/status'));
```

**Comment by pemartins** [comment]
Funcionou! Valeu!!!!

**Comment by caioschiavo** [comment]
se não tiver usando Curl

coloque 

`ini_set('user_agent', 'PHP');`

no inicio do código

**Comment by jhonata-menezes** [comment]
Se caso interessar, recomendo usar o [Guzzle](https://packagist.org/packages/guzzlehttp/guzzle) para requisições http.

**Comment by giovanigenerali** [comment]
https://github.com/wgenial/cartrolandofc#atenção

### Atenção

Dúvidas não relacionadas ao projeto como instalação, dúvidas de programação etc.. não serão respondidas e a issue será fechada. Agradeço a compreensão, obrigado.
