### ISSUE TITLE
Ajuda por favor!

### ISSUE THREAD

**Issue by lucascavalcante0398** [wgenial/cartrolandofc#55]
Eu não sou especialista em programação, porem após fazer a aplicação está ocorrendo este erro, teria como me esclarecer por favor !?
![capturar](https://cloud.githubusercontent.com/assets/28565060/25851320/af7d5556-349b-11e7-837d-139cd722540f.PNG)

**Comment by jhonata-menezes** [comment]
Esta dizendo que o caracter '<' não era esperado, posta o js para dar uma olhada.

**Comment by lucascavalcante0398** [comment]
É o mesmo que baixei do repositório! Que está neste link: https://github.com/wgenial/cartrolandofc/blob/master/build/js/scripts-1493599861.min.js

**Comment by phcamargo23** [comment]
Instalou as dependências? (composer e npm install)

**Comment by giovanigenerali** [comment]
https://github.com/wgenial/cartrolandofc#atenção

### Atenção
Dúvidas não relacionadas ao projeto como instalação, dúvidas de programação etc.. não serão respondidas e a issue será fechada. Agradeço a compreensão, obrigado.
