### ISSUE TITLE
Pontuação dos atletas

### ISSUE THREAD

**Issue by giovanigenerali** [wgenial/cartrolandofc#56]
### Sugestão

- Criar um script que armazene a pontuação de cada atleta por rodada, ano passado chegou na 13 rodada as anteriores acho que eles tiraram da API. 

- O script rodaria semanalmente após o fechamento da rodada para coletar esses dados, eu gostaria de fazer mas estou sem tempo. 

- Disponibilizar esses dados via API, exemplo:
  - Retornar a pontuação do atleta de rodada específica:
http://URLAPI/pontuacao/atleta/ID/rodada/ID
  - Retornar a pontuação do atleta em todas as rodadas:
http://URLAPI/pontuacao/atleta/ID

**Consigo disponibilizar o seguinte:**
- banco de dados mySQL 5.6.34
- crontab para agendar o script de coleta dos dados.
- publicar o script e a api nesse domínio http://www.cartrolandofc.cf/api/...

Quem tiver interesse em contribuir só avisar aqui, obrigado.

**Comment by jhonata-menezes** [comment]
O Mysql é a versão 5.7 ou superior? O campo json pode ajudar nessa funcionalidade.

**Comment by giovanigenerali** [comment]
@jhonata-menezes ainda versão 5.6.34

**Comment by jhonata-menezes** [comment]
Quais dados de retorno da api?
rodada, atleta_id, apelido,pontuacao, scout, foto, posicao_id, clube_id

Quais seriam os dados de retorno? Ao meu ver rodada, atleta_id e pontuação são obrigatórios. os outros seriam necessarios? Estou iniciando a implementação.

**Comment by giovanigenerali** [comment]
@jhonata-menezes acho que se retornar o padrão só do nó de atletas já existente ajuda. Quem precisar de mais dados vão contribuindo também. Depois me passa seu contato email pra te passar os dados de acesso do host, db, etc...

**Comment by jhonata-menezes** [comment]
jhonatamenezes10@gmail.com

**Comment by gustavodemari** [comment]
Talvez o ideal seja armazenar o json inteiro, por rodadas.

Aí não vão faltar os dados depois.

Inclusive, vocês sabem onde posso encontrar estatísticas dos anos anteriores?

Queria algo bem nessa linha aqui.

https://github.com/thevtm/CartolaFCDados

Obrigado

**Comment by jhonata-menezes** [comment]
irei tentar adicionar esse histórico também.

**Comment by jhonata-menezes** [comment]
Era o esperado para o endpoint /pontuacao/atleta/ID ?
![image](https://cloud.githubusercontent.com/assets/7094378/25976943/5a9158f4-368e-11e7-89d7-02797a06bd7a.png)

**Comment by gustavodemari** [comment]
No meu caso, queria uma foto de cada rodada mesmo, com todas as informações.

Gols, Passes Errados e etc.

Um banco de dados por rodada, pra criar um banco de dados do campeonato inteiro.

**Comment by phcamargo23** [comment]
Idem o comentário anterior. Sério, eu já procurei essas informações de gols, assistências, cartões, etc nas endpoints, baixei o código-fonte para verificar e... até agora eu não sei de onde elas vem. Alguém pode ajudar?

**Comment by giovanigenerali** [comment]
Nesse aqui vai mostrar as info. da rodada atual https://api.cartolafc.globo.com/atletas/mercado com isso poderia armazenar todo esse json a cada rodada.Veja a chave "rodada_id": 1

```
{
  "atletas": [
    {
      "nome": "Paulo Autuori",
      "apelido": "Paulo Autuori",
      "foto": "https://s.glbimg.com/es/sde/f/2017/04/23/51bd7e83b21a81fb576ba2321746e749_FORMATO.png",
      "atleta_id": 36943,
      "rodada_id": 1,
      "clube_id": 293,
      "posicao_id": 6,
      "status_id": 7,
      "pontos_num": 0,
      "preco_num": 10,
      "variacao_num": 0,
      "media_num": 0,
      "jogos_num": 0,
      "scout": {
        
      }
    },
```

**Comment by phcamargo23** [comment]
@giovanigenerali, desculpe minha ignorância ou caso eu esteja sendo desatento em algum ponto, mas essas informações dos gols, assistências, cartões, etc são disponibilizados ou não? Porque https://api.cartolafc.globo.com/partidas/1 também não tem nada. Valeu.

**Comment by giovanigenerali** [comment]
@phcamargo23 esses dados vem na chave scout que ainda está vazia não tem a rodada 1 fechada. o game não começou!
```
"scout": {
        
      }
```
Quando a rodada 1 estiver em andamento "mercado fechado" as informações em tempo real poderão ser consultadas nesse https://api.cartolafc.globo.com/atletas/pontuados que também vai trazer a chave "scout".

**Comment by jhonata-menezes** [comment]
Andamento da funcionalidade: https://github.com/jhonata-menezes/cartrolandofc/commits/master

**Comment by giovanigenerali** [comment]
o @jhonata-menezes fez uma versão inicial dessa feature e está no branch api. obrigado pela contribuição e quem quiser ajudar fique à vontade também ;)

**Comment by nenzinho** [comment]
Alguém pode dar uma força? Por que está dando erro no meu script?
`<?php
    $json_str = file_get_contents("https://api.cartolafc.globo.com/time/slug/volupia-monstra"); 
    $jsonObj = json_decode($json_str);
    $atletas = $jsonObj->atletas;
    $v = 0.0;
    foreach ($atletas as $e) {
        echo $e->pontos_num ." - ". $e->apelido . "<br>"; 
        $v += $e->pontos_num;
    }
    echo $v;
?>`

O erro é esse: Warning: file_get_contents(https://api.cartolafc.globo.com/time/slug/volupia-monstra) [function.file-get-contents]: failed to open stream: HTTP request failed! in C:\Users\Randerson\Downloads\USBWebserver v8.5\8.5\root\index.php on line 2

**Comment by giovanigenerali** [comment]
@nenzinho acesse https://gitter.im/cartrolandofc/dev lá o pessoal pode te ajudar sobre dúvidas de programação.
