### ISSUE TITLE
Numero de times em liga

### ISSUE THREAD

**Issue by ghost** [wgenial/cartrolandofc#58]
Quando acesso uma liga o numero máximo de times dentro da liga é de 20. Se eu tiver uma liga com mais de 20 times ele me retorna só 20, alguém sabe porque acontece isso?

usei como base uma liga qualquer : https://api.cartolafc.globo.com/auth/liga/bandeslliga

**Comment by giovanigenerali** [comment]
@SportsMobile https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php#L12-L33 tem que usar paginação:

- 20 times
http://www.cartrolandofc.cf/load-api-auth.php?api=liga&liga_slug=bandeslliga&page=1
- +4 times
http://www.cartrolandofc.cf/load-api-auth.php?api=liga&liga_slug=bandeslliga&page=2

Em qualquer uma das chamadas vai saber o total de times "total_times_liga": 24, como são 20 por páginas você consegue saber quantas página terá que chamar.

**Comment by ghost** [comment]
Obrigado meu caro!

**Comment by giovanigenerali** [comment]
🤘
