### ISSUE TITLE
Grupo para dúvidas

### ISSUE THREAD

**Issue by jhonata-menezes** [wgenial/cartrolandofc#59]
Boa noite, vejo que muita gente tem dúvida com relação a API do cartola, o que acham de criarmos um grupo para discussões assim evita criar issues para tirar dúvidas da API.

Existe Slack, Telegram, [gitter](https://gitter.im/) (esse eu nunca usei) e até Whatsapp. Fica sugestão, opinem o que vocês acham e se houver alguma ferramenta mais adequada para o propósito indiquem.

Obrigado.

**Comment by giovanigenerali** [comment]
@jhonata-menezes criado no gitter https://gitter.im/cartrolandofc/dev

**Comment by jhonata-menezes** [comment]
👍👍
