### ISSUE TITLE
Time correto mas mantém a pontuação da 1 rodada

### ISSUE THREAD

**Issue by caioschiavo** [wgenial/cartrolandofc#6]
A busca pelo time está correta o mercado fechou e já aparece o meu time da 2 rodada. Mas o sistema manteve as parciais da 1 rodada

**Comment by giovanigenerali** [comment]
@caioschiavo corrigido, agora está consultando a pontuação do time da rodada em andamento.

**Comment by roomoraaes** [comment]
http://www.variosgoles.com.br/parciais

Tudo funcionando ok no meu site.

**Comment by giovanigenerali** [comment]
@roomoraaes agora o script está consultando aqui https://api.cartolafc.globo.com/atletas/pontuados para pegar a pontuação da rodada atual. Antes estava pegando a pontuação que vem na consulta do time, que é a pontuação da rodada anterior. vlw

**Comment by roomoraaes** [comment]
Exatamente @giovanigenerali

**Comment by nenzinho** [comment]
@roomoraaes , seu projeto é muito bom. Teria como postar algo que desenvolveu pra gente ver?
