### ISSUE TITLE
curl -X trava após 3 requisições

### ISSUE THREAD

**Issue by rax59** [wgenial/cartrolandofc#64]
Olá Pessoal,

Tenho um website que utiliza esta api para apresentar as parciais do cartolafc da minha liga.
www.softw.in/cartolafc.

Desde 2016 utilizo e modifico o website para melhorias,principalmente as destacadas aqui.

Depois do início do cartolaFC notei que as requisições do curl travam após 3 comandos seguidos.

Será que a API cartola verifica a origem das solicitações para evitar solicitações em massa de um mesmo IP?

Saudações.

**Comment by giovanigenerali** [comment]
@rax59 por favor, acesse o [gitter](https://gitter.im/cartrolandofc/dev) para dúvidas.

**Comment by rax59** [comment]
"Não é possível acessar esse site
A página da web em https://gitter.im/cartrolandofc/dev"

**Comment by giovanigenerali** [comment]
@rax59 desloga da sua conta do github, limpa o cache do browser e tenta novamente. o pessoal consegue o acesso normal eu tbm.

**Comment by rax59** [comment]
Grato @giovanigenerali ,
talvez seja também problema de proxy.
Vou verificar.
Abs
