### ISSUE TITLE
Patrimônio por Time

### ISSUE THREAD

**Issue by marceloneumann** [wgenial/cartrolandofc#66]
Olá galera... Montei uma planilha do Excel para registrar os dados sobre a minha liga. Primeiramente para buscar os registros de JSON através do Excel, tive que instalar o suplemento Power Query, pois somente ele consegue importar essas informações nesta fonte de dados. Consegui buscar os dados de pontuações, nome, esquema, etc. tudo pelo link "https://api.cartolafc.globo.com/time/slug/[SLUG]"... Porém neste link não fornece o patrimônio! Não sei se alguém conhece o Power Query, mas caso exista outra forma de conseguir o patrimônio, mesmo que com autenticação, favor me informem. Estou anexando algumas telas para analisar. Aguardo retorno e agradeço!

![a](https://cloud.githubusercontent.com/assets/29071877/26601309/ce07dd3c-4555-11e7-83cc-df233706a42d.PNG)
![b](https://cloud.githubusercontent.com/assets/29071877/26601310/ce0c8a4e-4555-11e7-8a4e-8bf03e21c50a.PNG)
![c](https://cloud.githubusercontent.com/assets/29071877/26601311/ce0e13e6-4555-11e7-81a0-6b0862333d40.PNG)
![d](https://cloud.githubusercontent.com/assets/29071877/26601312/ce13f130-4555-11e7-8f1c-d816507bd3ae.PNG)

**Comment by giovanigenerali** [comment]
@marceloneumann por favor, envie suas dúvidas no gitter https://gitter.im/cartrolandofc/dev
