### ISSUE TITLE
Como consultar todos os times da Liga

### ISSUE THREAD

**Issue by thiagoramalho** [wgenial/cartrolandofc#7]
Olá! Primeiro parabéns pelo cartrolandofc, foi o único projeto que vi abordando sobre a API do cartola.

Percebi que a parte pública da api é limitada.

Como faço para pegar todos os times de uma liga, pode me ajudar?

**Comment by roomoraaes** [comment]
https://github.com/wgenial/cartrolandofc/issues/4

**Comment by giovanigenerali** [comment]
@thiagoramalho segue exemplo [http://cartrolandofc.com/load-api-auth.php?api=liga&liga_slug=liga-do-ge](http://cartrolandofc.com/load-api-auth.php?api=liga&liga_slug=liga-do-ge)

Para mais informações consulte esse arquivo [https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php](https://github.com/wgenial/cartrolandofc/blob/master/load-api-auth.php). Dá para utilizar filtro de ordenação e paginação.

``` code
orderBy: campeonato, turno, mes, rodada, patrimonio
page: 1, 2, 3...
```

@roomoraaes dá uma olhada nos meus últimos commits [https://github.com/wgenial/cartrolandofc/commit/0cdd3dda295fdc88587d0bcea255f0a0c160bb5e](https://github.com/wgenial/cartrolandofc/commit/0cdd3dda295fdc88587d0bcea255f0a0c160bb5e) e [https://github.com/wgenial/cartrolandofc/commit/8eede488dc6c7ec6195a2e203bd9edc028c98ec8](https://github.com/wgenial/cartrolandofc/commit/8eede488dc6c7ec6195a2e203bd9edc028c98ec8), coloquei exemplo de autenticação para pegar o token e fazer as chamadas privadas.

**Comment by caioschiavo** [comment]
@giovanigenerali vc sabe se através deste exemplo que vc postou, dá pra consultar as posições dos times durante a rodada em tempo real, ou eu teria que puxa time por time e seus respectivos jogadores, e somar as parciais dos jogadores de cada time?

**Comment by giovanigenerali** [comment]
@caioschiavo vc diz a posição do time dentro da liga e ainda na rodada em andamento? isso não tem, assim seria moleza e muito mastigado! tem que gastar os dedos e codar isso...

Eu acho que daria para puxar os times da liga que vc quer, depois pegar cada jogador de cada time e consultar aqui [https://api.cartolafc.globo.com/atletas/pontuados](https://api.cartolafc.globo.com/atletas/pontuados). 

Feito isso, vc faz os cálculos para fechar a pontuação de cada time e ordena no seu ranking.

Acho que seria uma opção, depende da sua necessidade. Qlq coisa posta ai para o povo ajudar tbm!

**Comment by caioschiavo** [comment]
@giovanigenerali foi o que eu imaginei..rs

Vou ver o que consigo e vou postando aqui sim
