### ISSUE TITLE
Mais informações sobre API

### ISSUE THREAD

**Issue by thiagoramalho** [wgenial/cartrolandofc#9]
Giovani! Todas suas dicas foram muito boas. Deu tudo certo até agora!

Meu questionamento agora é sobre:

Onde você obtém informações sobre a API? Como conseguiu informações dessas url?

Fico aqui pensando em fazer algo a mais na minha aplicação e tenho que ficar te perturbando por aqui. :)

1- Sabe se tem alguma url que quando eu faço login já me retorna as informações do time, as ligas que ele faz parte, etc?
2 - Informações sobre o mercado, se está aberto ou fechado.

Já vi alguns aplicativos que tem essas informações. Você tem mais conhecimento dessa API ou alguma documentação?

Obrigado.
[]'s

**Comment by giovanigenerali** [comment]
@thiagoramalho nesse arquivo [https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md](https://github.com/wgenial/cartrolandofc/blob/master/nova-api.md) tem mais info sobre a API. Além disso você pode fazer [aquelas chamadas](https://github.com/wgenial/cartrolandofc/issues/7) usando token para acessar as urls que são restritas.
